/*
 * Generated by web/scripts/generate-deflection-snapshot-contract.mjs.
 * Source: ATLAS portfolio-ui/src/types/deflectionReportModel.ts,
 * generated from the backend deflection report contract.
 * Do not edit by hand; run npm --prefix web run generate:deflection-contracts.
 */

export const DEFLECTION_REPORT_MODEL_SCHEMA_VERSION = "deflection.v1" as const;
export const DEFLECTION_REPORT_MODEL_FIELDS = ["schema_version", "title", "summary", "sections"] as const;
export const DEFLECTION_REPORT_SECTION_FIELDS = ["id", "title", "priority", "surfaces", "default_limit", "required_data", "snapshot_safe_fields", "data"] as const;
export const DEFLECTION_REPORT_SECTION_IDS = ["support_tax", "source_file", "seo_targets", "ranked_questions", "priority_fix_queue", "top_unresolved_repeats", "drafted_resolutions", "already_covered_still_recurring", "backlog_table", "outcome_diagnostics", "suppressed_repeat_review_queue", "question_details", "complete_evidence"] as const;
export const DEFLECTION_REPORT_CONDITIONAL_SECTION_IDS = ["source_file", "outcome_diagnostics"] as const;
export const DEFLECTION_REPORT_SUPPORT_TAX_FIELDS = ["repeat_ticket_count", "non_repeat_ticket_count", "generated_question_count", "assisted_contact_cost", "estimated_support_cost", "source_date_window", "drafted_answer_count", "no_proven_answer_count", "ticket_source_count", "annualized_support_cost", "annualized_run_rate_support_cost"] as const;
export const DEFLECTION_REPORT_SUPPORT_TAX_OPTIONAL_FIELDS = ["annualized_support_cost", "annualized_run_rate_support_cost"] as const;
export const DEFLECTION_REPORT_SUPPORT_TAX_REQUIRED_DATA = ["repeat_ticket_count", "non_repeat_ticket_count", "generated_question_count", "assisted_contact_cost", "estimated_support_cost", "source_date_window", "drafted_answer_count", "no_proven_answer_count", "ticket_source_count"] as const;
export const DEFLECTION_REPORT_SUPPORT_TAX_SNAPSHOT_SAFE_FIELDS = ["repeat_ticket_count", "non_repeat_ticket_count", "generated_question_count", "drafted_answer_count", "no_proven_answer_count", "ticket_source_count", "source_date_window"] as const;
export const DEFLECTION_REPORT_SUPPORT_TAX_HOSTED_CONSUMER_SAFE_FIELDS = ["repeat_ticket_count", "non_repeat_ticket_count", "generated_question_count", "assisted_contact_cost", "estimated_support_cost", "source_date_window", "drafted_answer_count", "no_proven_answer_count", "ticket_source_count", "annualized_support_cost", "annualized_run_rate_support_cost"] as const;
export const DEFLECTION_REPORT_SOURCE_FILE_FIELDS = ["source_label"] as const;
export const DEFLECTION_REPORT_SOURCE_FILE_REQUIRED_DATA = ["source_label"] as const;
export const DEFLECTION_REPORT_SOURCE_FILE_SNAPSHOT_SAFE_FIELDS = [] as const;
export const DEFLECTION_REPORT_SOURCE_FILE_HOSTED_CONSUMER_SAFE_FIELDS = [] as const;
export const DEFLECTION_REPORT_SEO_TARGETS_FIELDS = ["phrases", "total_phrase_count", "displayed_phrase_count", "omitted_phrase_count", "limit"] as const;
export const DEFLECTION_REPORT_SEO_TARGETS_REQUIRED_DATA = ["phrases", "total_phrase_count", "displayed_phrase_count", "omitted_phrase_count", "limit"] as const;
export const DEFLECTION_REPORT_SEO_TARGETS_SNAPSHOT_SAFE_FIELDS = [] as const;
export const DEFLECTION_REPORT_SEO_TARGETS_HOSTED_CONSUMER_SAFE_FIELDS = ["phrases", "total_phrase_count", "displayed_phrase_count", "omitted_phrase_count", "limit"] as const;
export const DEFLECTION_REPORT_RANKED_QUESTIONS_FIELDS = ["rows"] as const;
export const DEFLECTION_REPORT_RANKED_QUESTIONS_REQUIRED_DATA = ["rows"] as const;
export const DEFLECTION_REPORT_RANKED_QUESTIONS_SNAPSHOT_SAFE_FIELDS = ["rows.rank", "rows.question", "rows.ticket_count", "rows.weighted_frequency", "rows.customer_wording"] as const;
export const DEFLECTION_REPORT_RANKED_QUESTIONS_HOSTED_CONSUMER_SAFE_FIELDS = ["rows"] as const;
export const DEFLECTION_REPORT_RANKED_QUESTIONS_ROWS_HOSTED_CONSUMER_SAFE_FIELDS = ["rank", "question", "ticket_count", "weighted_frequency", "customer_wording", "estimated_support_cost", "opportunity_score", "answer_status", "source_proof"] as const;
export const DEFLECTION_REPORT_RANKED_QUESTIONS_ROWS_FIELDS = ["rank", "question", "ticket_count", "weighted_frequency", "customer_wording", "estimated_support_cost", "opportunity_score", "answer_status", "source_proof"] as const;
export const DEFLECTION_REPORT_PRIORITY_FIX_QUEUE_FIELDS = ["items", "status_counts", "result_page_limit", "pdf_limit", "backlog_limit", "support_cost_basis"] as const;
export const DEFLECTION_REPORT_PRIORITY_FIX_QUEUE_REQUIRED_DATA = ["items", "status_counts", "result_page_limit", "pdf_limit", "backlog_limit", "support_cost_basis"] as const;
export const DEFLECTION_REPORT_PRIORITY_FIX_QUEUE_SNAPSHOT_SAFE_FIELDS = [] as const;
export const DEFLECTION_REPORT_PRIORITY_FIX_QUEUE_HOSTED_CONSUMER_SAFE_FIELDS = ["items", "status_counts", "result_page_limit", "pdf_limit", "backlog_limit", "support_cost_basis"] as const;
export const DEFLECTION_REPORT_PRIORITY_FIX_QUEUE_SUPPORT_COST_BASIS_HOSTED_CONSUMER_SAFE_FIELDS = ["status"] as const;
export const DEFLECTION_REPORT_PRIORITY_FIX_QUEUE_ITEMS_HOSTED_CONSUMER_SAFE_FIELDS = ["rank", "question", "status", "owner_lane", "confidence", "recommended_action", "ticket_count", "estimated_support_cost", "priority_score", "priority_drivers", "csat_signal"] as const;
export const DEFLECTION_REPORT_PRIORITY_FIX_QUEUE_ITEMS_CSAT_SIGNAL_HOSTED_CONSUMER_SAFE_FIELDS = ["status", "csat_present_count", "negative_csat_ticket_count", "numeric_average"] as const;
export const DEFLECTION_REPORT_PRIORITY_FIX_QUEUE_ITEMS_TOP_EVIDENCE_HOSTED_CONSUMER_SAFE_FIELDS = [] as const;
export const DEFLECTION_REPORT_PRIORITY_FIX_QUEUE_ITEMS_FIELDS = ["rank", "repeat_key", "cluster_id", "identity_basis", "identity_confidence", "question", "status", "owner_lane", "fix_type", "csat_signal", "confidence", "priority_score", "priority_drivers", "recommended_title", "recommended_action", "representative_phrasing", "ticket_count", "estimated_support_cost", "support_cost_formula", "support_cost_source", "opportunity_score", "top_evidence"] as const;
export const DEFLECTION_REPORT_TOP_UNRESOLVED_REPEATS_FIELDS = ["items", "top_item_count", "result_page_limit", "pdf_limit", "support_cost_basis"] as const;
export const DEFLECTION_REPORT_TOP_UNRESOLVED_REPEATS_REQUIRED_DATA = ["items", "top_item_count", "result_page_limit", "pdf_limit", "support_cost_basis"] as const;
export const DEFLECTION_REPORT_TOP_UNRESOLVED_REPEATS_SNAPSHOT_SAFE_FIELDS = ["items.rank", "items.question", "items.ticket_count"] as const;
export const DEFLECTION_REPORT_TOP_UNRESOLVED_REPEATS_HOSTED_CONSUMER_SAFE_FIELDS = ["items", "top_item_count", "support_cost_basis"] as const;
export const DEFLECTION_REPORT_TOP_UNRESOLVED_REPEATS_SUPPORT_COST_BASIS_HOSTED_CONSUMER_SAFE_FIELDS = ["status"] as const;
export const DEFLECTION_REPORT_TOP_UNRESOLVED_REPEATS_ITEMS_HOSTED_CONSUMER_SAFE_FIELDS = ["rank", "question", "status", "owner_lane", "confidence", "recommended_action", "ticket_count", "estimated_support_cost", "priority_score", "priority_drivers", "csat_signal"] as const;
export const DEFLECTION_REPORT_TOP_UNRESOLVED_REPEATS_ITEMS_CSAT_SIGNAL_HOSTED_CONSUMER_SAFE_FIELDS = ["status", "csat_present_count", "negative_csat_ticket_count", "numeric_average"] as const;
export const DEFLECTION_REPORT_TOP_UNRESOLVED_REPEATS_ITEMS_TOP_EVIDENCE_HOSTED_CONSUMER_SAFE_FIELDS = [] as const;
export const DEFLECTION_REPORT_TOP_UNRESOLVED_REPEATS_ITEMS_FIELDS = ["rank", "repeat_key", "cluster_id", "identity_basis", "identity_confidence", "question", "status", "owner_lane", "fix_type", "csat_signal", "confidence", "priority_score", "priority_drivers", "recommended_title", "recommended_action", "representative_phrasing", "ticket_count", "estimated_support_cost", "support_cost_formula", "support_cost_source", "opportunity_score", "top_evidence"] as const;
export const DEFLECTION_REPORT_DRAFTED_RESOLUTIONS_FIELDS = ["items", "top_item_count", "result_page_limit", "pdf_limit"] as const;
export const DEFLECTION_REPORT_DRAFTED_RESOLUTIONS_REQUIRED_DATA = ["items", "top_item_count", "result_page_limit", "pdf_limit"] as const;
export const DEFLECTION_REPORT_DRAFTED_RESOLUTIONS_SNAPSHOT_SAFE_FIELDS = [] as const;
export const DEFLECTION_REPORT_DRAFTED_RESOLUTIONS_HOSTED_CONSUMER_SAFE_FIELDS = ["items", "top_item_count"] as const;
export const DEFLECTION_REPORT_DRAFTED_RESOLUTIONS_ITEMS_HOSTED_CONSUMER_SAFE_FIELDS = ["rank", "question", "status", "owner_lane", "confidence", "recommended_action", "ticket_count", "estimated_support_cost", "priority_score", "priority_drivers", "csat_signal"] as const;
export const DEFLECTION_REPORT_DRAFTED_RESOLUTIONS_ITEMS_CSAT_SIGNAL_HOSTED_CONSUMER_SAFE_FIELDS = ["status", "csat_present_count", "negative_csat_ticket_count", "numeric_average"] as const;
export const DEFLECTION_REPORT_DRAFTED_RESOLUTIONS_ITEMS_TOP_EVIDENCE_HOSTED_CONSUMER_SAFE_FIELDS = [] as const;
export const DEFLECTION_REPORT_DRAFTED_RESOLUTIONS_ITEMS_FIELDS = ["rank", "repeat_key", "cluster_id", "identity_basis", "identity_confidence", "question", "status", "owner_lane", "fix_type", "csat_signal", "confidence", "priority_score", "priority_drivers", "recommended_title", "recommended_action", "representative_phrasing", "ticket_count", "estimated_support_cost", "support_cost_formula", "support_cost_source", "opportunity_score", "top_evidence"] as const;
export const DEFLECTION_REPORT_ALREADY_COVERED_STILL_RECURRING_FIELDS = ["items", "top_item_count", "result_page_limit", "pdf_limit"] as const;
export const DEFLECTION_REPORT_ALREADY_COVERED_STILL_RECURRING_REQUIRED_DATA = ["items", "top_item_count", "result_page_limit", "pdf_limit"] as const;
export const DEFLECTION_REPORT_ALREADY_COVERED_STILL_RECURRING_SNAPSHOT_SAFE_FIELDS = [] as const;
export const DEFLECTION_REPORT_ALREADY_COVERED_STILL_RECURRING_HOSTED_CONSUMER_SAFE_FIELDS = ["items", "top_item_count"] as const;
export const DEFLECTION_REPORT_ALREADY_COVERED_STILL_RECURRING_ITEMS_HOSTED_CONSUMER_SAFE_FIELDS = ["rank", "question", "status", "owner_lane", "confidence", "recommended_action", "ticket_count", "estimated_support_cost", "priority_score", "priority_drivers", "csat_signal"] as const;
export const DEFLECTION_REPORT_ALREADY_COVERED_STILL_RECURRING_ITEMS_CSAT_SIGNAL_HOSTED_CONSUMER_SAFE_FIELDS = ["status", "csat_present_count", "negative_csat_ticket_count", "numeric_average"] as const;
export const DEFLECTION_REPORT_ALREADY_COVERED_STILL_RECURRING_ITEMS_TOP_EVIDENCE_HOSTED_CONSUMER_SAFE_FIELDS = [] as const;
export const DEFLECTION_REPORT_ALREADY_COVERED_STILL_RECURRING_ITEMS_FIELDS = ["rank", "repeat_key", "cluster_id", "identity_basis", "identity_confidence", "question", "status", "owner_lane", "fix_type", "csat_signal", "confidence", "priority_score", "priority_drivers", "recommended_title", "recommended_action", "representative_phrasing", "ticket_count", "estimated_support_cost", "support_cost_formula", "support_cost_source", "opportunity_score", "top_evidence"] as const;
export const DEFLECTION_REPORT_BACKLOG_TABLE_FIELDS = ["items", "total_item_count", "default_limit"] as const;
export const DEFLECTION_REPORT_BACKLOG_TABLE_REQUIRED_DATA = ["items", "total_item_count", "default_limit"] as const;
export const DEFLECTION_REPORT_BACKLOG_TABLE_SNAPSHOT_SAFE_FIELDS = [] as const;
export const DEFLECTION_REPORT_BACKLOG_TABLE_HOSTED_CONSUMER_SAFE_FIELDS = ["items", "total_item_count", "default_limit"] as const;
export const DEFLECTION_REPORT_BACKLOG_TABLE_ITEMS_HOSTED_CONSUMER_SAFE_FIELDS = ["rank", "question", "status", "owner_lane", "confidence", "recommended_action", "ticket_count", "estimated_support_cost", "priority_score", "priority_drivers", "csat_signal"] as const;
export const DEFLECTION_REPORT_BACKLOG_TABLE_ITEMS_CSAT_SIGNAL_HOSTED_CONSUMER_SAFE_FIELDS = ["status", "csat_present_count", "negative_csat_ticket_count", "numeric_average"] as const;
export const DEFLECTION_REPORT_BACKLOG_TABLE_ITEMS_TOP_EVIDENCE_HOSTED_CONSUMER_SAFE_FIELDS = [] as const;
export const DEFLECTION_REPORT_BACKLOG_TABLE_ITEMS_FIELDS = ["rank", "repeat_key", "cluster_id", "identity_basis", "identity_confidence", "question", "status", "owner_lane", "fix_type", "csat_signal", "confidence", "priority_score", "priority_drivers", "recommended_title", "recommended_action", "representative_phrasing", "ticket_count", "estimated_support_cost", "support_cost_formula", "support_cost_source", "opportunity_score", "top_evidence"] as const;
export const DEFLECTION_REPORT_OUTCOME_DIAGNOSTICS_FIELDS = ["outcome_diagnostic_ticket_count", "outcome_risk_ticket_count", "reopened_ticket_count", "negative_csat_ticket_count", "rows"] as const;
export const DEFLECTION_REPORT_OUTCOME_DIAGNOSTICS_REQUIRED_DATA = ["outcome_diagnostic_ticket_count", "outcome_risk_ticket_count", "reopened_ticket_count", "negative_csat_ticket_count", "rows"] as const;
export const DEFLECTION_REPORT_OUTCOME_DIAGNOSTICS_SNAPSHOT_SAFE_FIELDS = [] as const;
export const DEFLECTION_REPORT_OUTCOME_DIAGNOSTICS_HOSTED_CONSUMER_SAFE_FIELDS = ["outcome_diagnostic_ticket_count", "outcome_risk_ticket_count", "reopened_ticket_count", "negative_csat_ticket_count", "rows"] as const;
export const DEFLECTION_REPORT_OUTCOME_DIAGNOSTICS_ROWS_HOSTED_CONSUMER_SAFE_FIELDS = ["question", "status_mix", "reopened_ticket_count", "negative_csat_ticket_count", "guidance"] as const;
export const DEFLECTION_REPORT_OUTCOME_DIAGNOSTICS_ROWS_FIELDS = ["question", "status_mix", "reopened_ticket_count", "negative_csat_ticket_count", "guidance"] as const;
export const DEFLECTION_REPORT_SUPPRESSED_REPEAT_REVIEW_QUEUE_FIELDS = ["items", "total_item_count", "default_limit", "reason_counts"] as const;
export const DEFLECTION_REPORT_SUPPRESSED_REPEAT_REVIEW_QUEUE_REQUIRED_DATA = ["items", "total_item_count", "default_limit", "reason_counts"] as const;
export const DEFLECTION_REPORT_SUPPRESSED_REPEAT_REVIEW_QUEUE_SNAPSHOT_SAFE_FIELDS = [] as const;
export const DEFLECTION_REPORT_SUPPRESSED_REPEAT_REVIEW_QUEUE_HOSTED_CONSUMER_SAFE_FIELDS = ["items", "total_item_count", "default_limit", "reason_counts"] as const;
export const DEFLECTION_REPORT_SUPPRESSED_REPEAT_REVIEW_QUEUE_ITEMS_HOSTED_CONSUMER_SAFE_FIELDS = ["rank", "question", "status", "owner_lane", "confidence", "recommended_action", "ticket_count", "estimated_support_cost", "priority_score", "priority_drivers", "csat_signal", "review_key", "suppression_reason", "suppression_reason_label"] as const;
export const DEFLECTION_REPORT_SUPPRESSED_REPEAT_REVIEW_QUEUE_ITEMS_CSAT_SIGNAL_HOSTED_CONSUMER_SAFE_FIELDS = ["status", "csat_present_count", "negative_csat_ticket_count", "numeric_average"] as const;
export const DEFLECTION_REPORT_SUPPRESSED_REPEAT_REVIEW_QUEUE_ITEMS_TOP_EVIDENCE_HOSTED_CONSUMER_SAFE_FIELDS = [] as const;
export const DEFLECTION_REPORT_SUPPRESSED_REPEAT_REVIEW_QUEUE_ITEMS_FIELDS = ["rank", "repeat_key", "cluster_id", "identity_basis", "identity_confidence", "question", "status", "owner_lane", "fix_type", "csat_signal", "confidence", "priority_score", "priority_drivers", "recommended_title", "recommended_action", "representative_phrasing", "ticket_count", "estimated_support_cost", "support_cost_formula", "support_cost_source", "opportunity_score", "top_evidence", "review_key", "suppression_reason", "suppression_reason_label"] as const;
export const DEFLECTION_REPORT_QUESTION_DETAILS_FIELDS = ["rows"] as const;
export const DEFLECTION_REPORT_QUESTION_DETAILS_REQUIRED_DATA = ["rows"] as const;
export const DEFLECTION_REPORT_QUESTION_DETAILS_SNAPSHOT_SAFE_FIELDS = ["rows.rank", "rows.question", "rows.answer_evidence_status", "rows.resolution_evidence_scope", "rows.weighted_frequency", "rows.source_count"] as const;
export const DEFLECTION_REPORT_QUESTION_DETAILS_HOSTED_CONSUMER_SAFE_FIELDS = ["rows"] as const;
export const DEFLECTION_REPORT_QUESTION_DETAILS_ROWS_HOSTED_CONSUMER_SAFE_FIELDS = ["rank", "question", "customer_wording", "topic", "ticket_count", "weighted_frequency", "source_count", "estimated_support_cost", "answer_status", "answer_evidence_status", "resolution_evidence_scope", "answer_linkage", "answer", "steps", "term_mappings"] as const;
export const DEFLECTION_REPORT_QUESTION_DETAILS_ROWS_FIELDS = ["rank", "question", "customer_wording", "topic", "ticket_count", "weighted_frequency", "source_count", "estimated_support_cost", "answer_status", "answer_evidence_status", "resolution_evidence_scope", "answer_linkage", "answer", "steps", "term_mappings", "source_ids", "evidence_quotes", "outcome_diagnostics"] as const;
export const DEFLECTION_REPORT_COMPLETE_EVIDENCE_FIELDS = ["question_count", "evidence_row_count", "source_id_count", "surfaces"] as const;
export const DEFLECTION_REPORT_COMPLETE_EVIDENCE_REQUIRED_DATA = ["question_count", "evidence_row_count", "source_id_count", "surfaces"] as const;
export const DEFLECTION_REPORT_COMPLETE_EVIDENCE_SNAPSHOT_SAFE_FIELDS = [] as const;
export const DEFLECTION_REPORT_COMPLETE_EVIDENCE_HOSTED_CONSUMER_SAFE_FIELDS = [] as const;
export type DeflectionReportSourceDateWindow = {
    source_date_start: string | null;
    source_date_end: string | null;
    source_window_days: number | null;
};
export type DeflectionReportTermMapping = {
    customer_term: string;
    documentation_term: string;
    suggestion: string;
    source_id_count: number;
};
export type DeflectionReportQuestionOutcomeDiagnostics = {
    ticket_status_summary?: Record<string, number>;
    diagnostic_ticket_count?: number;
    outcome_risk_ticket_count?: number;
    reopened_ticket_count?: number;
    negative_csat_ticket_count?: number;
    csat_present_count?: number;
    csat_score_average?: number | null;
};
export type DeflectionReportSupportTaxData = {
    repeat_ticket_count: number;
    non_repeat_ticket_count: number;
    generated_question_count: number;
    assisted_contact_cost: number;
    estimated_support_cost: number;
    source_date_window: DeflectionReportSourceDateWindow | null;
    drafted_answer_count: number;
    no_proven_answer_count: number;
    ticket_source_count: number;
    annualized_support_cost?: number;
    annualized_run_rate_support_cost?: number;
};
export type DeflectionReportSupportTaxSection = {
    id: "support_tax";
    title: string;
    priority: number;
    surfaces: string[];
    default_limit: number | null;
    required_data: string[];
    snapshot_safe_fields: string[];
    data: DeflectionReportSupportTaxData;
};
export type DeflectionReportSourceFileData = {
    source_label: string;
};
export type DeflectionReportSourceFileSection = {
    id: "source_file";
    title: string;
    priority: number;
    surfaces: string[];
    default_limit: number | null;
    required_data: string[];
    snapshot_safe_fields: string[];
    data: DeflectionReportSourceFileData;
};
export type DeflectionReportSeoTargetsData = {
    phrases: string[];
    total_phrase_count: number;
    displayed_phrase_count: number;
    omitted_phrase_count: number;
    limit: number;
};
export type DeflectionReportSeoTargetsSection = {
    id: "seo_targets";
    title: string;
    priority: number;
    surfaces: string[];
    default_limit: number | null;
    required_data: string[];
    snapshot_safe_fields: string[];
    data: DeflectionReportSeoTargetsData;
};
export type DeflectionReportRankedQuestionsRow = {
    rank: number;
    question: string;
    ticket_count: number;
    weighted_frequency: number;
    customer_wording: string;
    estimated_support_cost: number;
    opportunity_score: number;
    answer_status: string;
    source_proof: string;
};
export type DeflectionReportRankedQuestionsData = {
    rows: DeflectionReportRankedQuestionsRow[];
};
export type DeflectionReportRankedQuestionsSection = {
    id: "ranked_questions";
    title: string;
    priority: number;
    surfaces: string[];
    default_limit: number | null;
    required_data: string[];
    snapshot_safe_fields: string[];
    data: DeflectionReportRankedQuestionsData;
};
export type DeflectionReportPriorityFixQueueSupportCostBasis = {
    status: string;
    assisted_contact_cost: number;
    formula: string;
    source: string;
};
export type DeflectionReportPriorityFixQueueCsatSignal = {
    status: string;
    csat_present_count: number;
    negative_csat_ticket_count: number;
    numeric_average: number | null;
};
export type DeflectionReportPriorityFixQueueTopEvidence = {
    source_id: string;
    evidence_quote: string;
};
export type DeflectionReportPriorityFixQueueItem = {
    rank: number;
    repeat_key: string;
    cluster_id: string;
    identity_basis: string;
    identity_confidence: string;
    question: string;
    status: string;
    owner_lane: string;
    fix_type: string;
    csat_signal: DeflectionReportPriorityFixQueueCsatSignal;
    confidence: string;
    priority_score: number;
    priority_drivers: string[];
    recommended_title: string;
    recommended_action: string;
    representative_phrasing: string;
    ticket_count: number;
    estimated_support_cost: number;
    support_cost_formula: string;
    support_cost_source: string;
    opportunity_score: number;
    top_evidence: DeflectionReportPriorityFixQueueTopEvidence[];
};
export type DeflectionReportPriorityFixQueueData = {
    items: DeflectionReportPriorityFixQueueItem[];
    status_counts: Record<string, number>;
    result_page_limit: number;
    pdf_limit: number;
    backlog_limit: number;
    support_cost_basis: DeflectionReportPriorityFixQueueSupportCostBasis;
};
export type DeflectionReportPriorityFixQueueSection = {
    id: "priority_fix_queue";
    title: string;
    priority: number;
    surfaces: string[];
    default_limit: number | null;
    required_data: string[];
    snapshot_safe_fields: string[];
    data: DeflectionReportPriorityFixQueueData;
};
export type DeflectionReportTopUnresolvedRepeatsSupportCostBasis = {
    status: string;
    assisted_contact_cost: number;
    formula: string;
    source: string;
};
export type DeflectionReportTopUnresolvedRepeatsCsatSignal = {
    status: string;
    csat_present_count: number;
    negative_csat_ticket_count: number;
    numeric_average: number | null;
};
export type DeflectionReportTopUnresolvedRepeatsTopEvidence = {
    source_id: string;
    evidence_quote: string;
};
export type DeflectionReportTopUnresolvedRepeatsItem = {
    rank: number;
    repeat_key: string;
    cluster_id: string;
    identity_basis: string;
    identity_confidence: string;
    question: string;
    status: string;
    owner_lane: string;
    fix_type: string;
    csat_signal: DeflectionReportTopUnresolvedRepeatsCsatSignal;
    confidence: string;
    priority_score: number;
    priority_drivers: string[];
    recommended_title: string;
    recommended_action: string;
    representative_phrasing: string;
    ticket_count: number;
    estimated_support_cost: number;
    support_cost_formula: string;
    support_cost_source: string;
    opportunity_score: number;
    top_evidence: DeflectionReportTopUnresolvedRepeatsTopEvidence[];
};
export type DeflectionReportTopUnresolvedRepeatsData = {
    items: DeflectionReportTopUnresolvedRepeatsItem[];
    top_item_count: number;
    result_page_limit: number;
    pdf_limit: number;
    support_cost_basis: DeflectionReportTopUnresolvedRepeatsSupportCostBasis;
};
export type DeflectionReportTopUnresolvedRepeatsSection = {
    id: "top_unresolved_repeats";
    title: string;
    priority: number;
    surfaces: string[];
    default_limit: number | null;
    required_data: string[];
    snapshot_safe_fields: string[];
    data: DeflectionReportTopUnresolvedRepeatsData;
};
export type DeflectionReportDraftedResolutionsCsatSignal = {
    status: string;
    csat_present_count: number;
    negative_csat_ticket_count: number;
    numeric_average: number | null;
};
export type DeflectionReportDraftedResolutionsTopEvidence = {
    source_id: string;
    evidence_quote: string;
};
export type DeflectionReportDraftedResolutionsItem = {
    rank: number;
    repeat_key: string;
    cluster_id: string;
    identity_basis: string;
    identity_confidence: string;
    question: string;
    status: string;
    owner_lane: string;
    fix_type: string;
    csat_signal: DeflectionReportDraftedResolutionsCsatSignal;
    confidence: string;
    priority_score: number;
    priority_drivers: string[];
    recommended_title: string;
    recommended_action: string;
    representative_phrasing: string;
    ticket_count: number;
    estimated_support_cost: number;
    support_cost_formula: string;
    support_cost_source: string;
    opportunity_score: number;
    top_evidence: DeflectionReportDraftedResolutionsTopEvidence[];
};
export type DeflectionReportDraftedResolutionsData = {
    items: DeflectionReportDraftedResolutionsItem[];
    top_item_count: number;
    result_page_limit: number;
    pdf_limit: number;
};
export type DeflectionReportDraftedResolutionsSection = {
    id: "drafted_resolutions";
    title: string;
    priority: number;
    surfaces: string[];
    default_limit: number | null;
    required_data: string[];
    snapshot_safe_fields: string[];
    data: DeflectionReportDraftedResolutionsData;
};
export type DeflectionReportAlreadyCoveredStillRecurringCsatSignal = {
    status: string;
    csat_present_count: number;
    negative_csat_ticket_count: number;
    numeric_average: number | null;
};
export type DeflectionReportAlreadyCoveredStillRecurringTopEvidence = {
    source_id: string;
    evidence_quote: string;
};
export type DeflectionReportAlreadyCoveredStillRecurringItem = {
    rank: number;
    repeat_key: string;
    cluster_id: string;
    identity_basis: string;
    identity_confidence: string;
    question: string;
    status: string;
    owner_lane: string;
    fix_type: string;
    csat_signal: DeflectionReportAlreadyCoveredStillRecurringCsatSignal;
    confidence: string;
    priority_score: number;
    priority_drivers: string[];
    recommended_title: string;
    recommended_action: string;
    representative_phrasing: string;
    ticket_count: number;
    estimated_support_cost: number;
    support_cost_formula: string;
    support_cost_source: string;
    opportunity_score: number;
    top_evidence: DeflectionReportAlreadyCoveredStillRecurringTopEvidence[];
};
export type DeflectionReportAlreadyCoveredStillRecurringData = {
    items: DeflectionReportAlreadyCoveredStillRecurringItem[];
    top_item_count: number;
    result_page_limit: number;
    pdf_limit: number;
};
export type DeflectionReportAlreadyCoveredStillRecurringSection = {
    id: "already_covered_still_recurring";
    title: string;
    priority: number;
    surfaces: string[];
    default_limit: number | null;
    required_data: string[];
    snapshot_safe_fields: string[];
    data: DeflectionReportAlreadyCoveredStillRecurringData;
};
export type DeflectionReportBacklogTableCsatSignal = {
    status: string;
    csat_present_count: number;
    negative_csat_ticket_count: number;
    numeric_average: number | null;
};
export type DeflectionReportBacklogTableTopEvidence = {
    source_id: string;
    evidence_quote: string;
};
export type DeflectionReportBacklogTableItem = {
    rank: number;
    repeat_key: string;
    cluster_id: string;
    identity_basis: string;
    identity_confidence: string;
    question: string;
    status: string;
    owner_lane: string;
    fix_type: string;
    csat_signal: DeflectionReportBacklogTableCsatSignal;
    confidence: string;
    priority_score: number;
    priority_drivers: string[];
    recommended_title: string;
    recommended_action: string;
    representative_phrasing: string;
    ticket_count: number;
    estimated_support_cost: number;
    support_cost_formula: string;
    support_cost_source: string;
    opportunity_score: number;
    top_evidence: DeflectionReportBacklogTableTopEvidence[];
};
export type DeflectionReportBacklogTableData = {
    items: DeflectionReportBacklogTableItem[];
    total_item_count: number;
    default_limit: number;
};
export type DeflectionReportBacklogTableSection = {
    id: "backlog_table";
    title: string;
    priority: number;
    surfaces: string[];
    default_limit: number | null;
    required_data: string[];
    snapshot_safe_fields: string[];
    data: DeflectionReportBacklogTableData;
};
export type DeflectionReportOutcomeDiagnosticsRow = {
    question: string;
    status_mix: Record<string, number>;
    reopened_ticket_count: number;
    negative_csat_ticket_count: number;
    guidance: string;
};
export type DeflectionReportOutcomeDiagnosticsData = {
    outcome_diagnostic_ticket_count: number;
    outcome_risk_ticket_count: number;
    reopened_ticket_count: number;
    negative_csat_ticket_count: number;
    rows: DeflectionReportOutcomeDiagnosticsRow[];
};
export type DeflectionReportOutcomeDiagnosticsSection = {
    id: "outcome_diagnostics";
    title: string;
    priority: number;
    surfaces: string[];
    default_limit: number | null;
    required_data: string[];
    snapshot_safe_fields: string[];
    data: DeflectionReportOutcomeDiagnosticsData;
};
export type DeflectionReportSuppressedRepeatReviewQueueCsatSignal = {
    status: string;
    csat_present_count: number;
    negative_csat_ticket_count: number;
    numeric_average: number | null;
};
export type DeflectionReportSuppressedRepeatReviewQueueTopEvidence = {
    source_id: string;
    evidence_quote: string;
};
export type DeflectionReportSuppressedRepeatReviewQueueItem = {
    rank: number;
    repeat_key: string;
    cluster_id: string;
    identity_basis: string;
    identity_confidence: string;
    question: string;
    status: string;
    owner_lane: string;
    fix_type: string;
    csat_signal: DeflectionReportSuppressedRepeatReviewQueueCsatSignal;
    confidence: string;
    priority_score: number;
    priority_drivers: string[];
    recommended_title: string;
    recommended_action: string;
    representative_phrasing: string;
    ticket_count: number;
    estimated_support_cost: number;
    support_cost_formula: string;
    support_cost_source: string;
    opportunity_score: number;
    top_evidence: DeflectionReportSuppressedRepeatReviewQueueTopEvidence[];
    review_key: string;
    suppression_reason: string;
    suppression_reason_label: string;
};
export type DeflectionReportSuppressedRepeatReviewQueueData = {
    items: DeflectionReportSuppressedRepeatReviewQueueItem[];
    total_item_count: number;
    default_limit: number;
    reason_counts: Record<string, number>;
};
export type DeflectionReportSuppressedRepeatReviewQueueSection = {
    id: "suppressed_repeat_review_queue";
    title: string;
    priority: number;
    surfaces: string[];
    default_limit: number | null;
    required_data: string[];
    snapshot_safe_fields: string[];
    data: DeflectionReportSuppressedRepeatReviewQueueData;
};
export type DeflectionReportQuestionDetailsRow = {
    rank: number;
    question: string;
    customer_wording: string;
    topic: string;
    ticket_count: number;
    weighted_frequency: number;
    source_count: number;
    estimated_support_cost: number;
    answer_status: string;
    answer_evidence_status: string;
    resolution_evidence_scope: string;
    answer_linkage: string;
    answer: string;
    steps: string[];
    term_mappings: DeflectionReportTermMapping[];
    source_ids: string[];
    evidence_quotes: string[];
    outcome_diagnostics: DeflectionReportQuestionOutcomeDiagnostics | null;
};
export type DeflectionReportQuestionDetailsData = {
    rows: DeflectionReportQuestionDetailsRow[];
};
export type DeflectionReportQuestionDetailsSection = {
    id: "question_details";
    title: string;
    priority: number;
    surfaces: string[];
    default_limit: number | null;
    required_data: string[];
    snapshot_safe_fields: string[];
    data: DeflectionReportQuestionDetailsData;
};
export type DeflectionReportCompleteEvidenceData = {
    question_count: number;
    evidence_row_count: number;
    source_id_count: number;
    surfaces: string[];
};
export type DeflectionReportCompleteEvidenceSection = {
    id: "complete_evidence";
    title: string;
    priority: number;
    surfaces: string[];
    default_limit: number | null;
    required_data: string[];
    snapshot_safe_fields: string[];
    data: DeflectionReportCompleteEvidenceData;
};
export type DeflectionReportSectionDataById = {
    support_tax: DeflectionReportSupportTaxData;
    source_file?: DeflectionReportSourceFileData;
    seo_targets: DeflectionReportSeoTargetsData;
    ranked_questions: DeflectionReportRankedQuestionsData;
    priority_fix_queue: DeflectionReportPriorityFixQueueData;
    top_unresolved_repeats: DeflectionReportTopUnresolvedRepeatsData;
    drafted_resolutions: DeflectionReportDraftedResolutionsData;
    already_covered_still_recurring: DeflectionReportAlreadyCoveredStillRecurringData;
    backlog_table: DeflectionReportBacklogTableData;
    outcome_diagnostics?: DeflectionReportOutcomeDiagnosticsData;
    suppressed_repeat_review_queue: DeflectionReportSuppressedRepeatReviewQueueData;
    question_details: DeflectionReportQuestionDetailsData;
    complete_evidence: DeflectionReportCompleteEvidenceData;
};
export type DeflectionReportSection = DeflectionReportSupportTaxSection | DeflectionReportSourceFileSection | DeflectionReportSeoTargetsSection | DeflectionReportRankedQuestionsSection | DeflectionReportPriorityFixQueueSection | DeflectionReportTopUnresolvedRepeatsSection | DeflectionReportDraftedResolutionsSection | DeflectionReportAlreadyCoveredStillRecurringSection | DeflectionReportBacklogTableSection | DeflectionReportOutcomeDiagnosticsSection | DeflectionReportSuppressedRepeatReviewQueueSection | DeflectionReportQuestionDetailsSection | DeflectionReportCompleteEvidenceSection;
export type DeflectionStructuredReport = {
    schema_version: typeof DEFLECTION_REPORT_MODEL_SCHEMA_VERSION;
    title: string;
    summary: Record<string, unknown>;
    sections: DeflectionReportSection[];
};
