/*
 * Generated by web/scripts/generate-deflection-snapshot-contract.mjs.
 * Source: ATLAS portfolio-ui/src/types/deflectionReportModel.ts,
 * generated from the backend deflection report contract.
 * Do not edit by hand; run npm --prefix web run generate:deflection-contracts.
 */

export const DEFLECTION_REPORT_MODEL_SCHEMA_VERSION = "deflection.v1" as const;
export const DEFLECTION_REPORT_MODEL_FIELDS = ["schema_version", "title", "summary", "sections"] as const;
export const DEFLECTION_REPORT_SECTION_FIELDS = ["id", "title", "priority", "surfaces", "default_limit", "required_data", "snapshot_safe_fields", "data"] as const;
export const DEFLECTION_REPORT_SECTION_IDS = ["support_tax", "source_file", "seo_targets", "ranked_questions", "priority_fix_queue", "top_unresolved_repeats", "drafted_resolutions", "already_covered_still_recurring", "backlog_table", "outcome_diagnostics", "suppressed_repeat_review_queue", "question_details", "complete_evidence"] as const;
export const DEFLECTION_REPORT_CONDITIONAL_SECTION_IDS = ["source_file", "outcome_diagnostics"] as const;
export const DEFLECTION_REPORT_SUPPORT_TAX_FIELDS = ["repeat_ticket_count", "non_repeat_ticket_count", "generated_question_count", "assisted_contact_cost", "estimated_support_cost", "source_date_window", "drafted_answer_count", "no_proven_answer_count", "ticket_source_count", "annualized_support_cost", "annualized_run_rate_support_cost"] as const;
export const DEFLECTION_REPORT_SUPPORT_TAX_OPTIONAL_FIELDS = ["annualized_support_cost", "annualized_run_rate_support_cost"] as const;
export const DEFLECTION_REPORT_SUPPORT_TAX_REQUIRED_DATA = ["repeat_ticket_count", "non_repeat_ticket_count", "generated_question_count", "assisted_contact_cost", "estimated_support_cost", "source_date_window", "drafted_answer_count", "no_proven_answer_count", "ticket_source_count"] as const;
export const DEFLECTION_REPORT_SUPPORT_TAX_SNAPSHOT_SAFE_FIELDS = ["repeat_ticket_count", "non_repeat_ticket_count", "generated_question_count", "drafted_answer_count", "no_proven_answer_count", "ticket_source_count", "source_date_window"] as const;
export const DEFLECTION_REPORT_SUPPORT_TAX_HOSTED_CONSUMER_SAFE_FIELDS = ["repeat_ticket_count", "non_repeat_ticket_count", "generated_question_count", "assisted_contact_cost", "estimated_support_cost", "source_date_window", "drafted_answer_count", "no_proven_answer_count", "ticket_source_count", "annualized_support_cost", "annualized_run_rate_support_cost"] as const;
export const DEFLECTION_REPORT_SUPPORT_TAX_SOURCE_DATE_WINDOW_HOSTED_CONSUMER_SAFE_FIELDS = ["source_date_start", "source_date_end", "source_window_days"] as const;
export const DEFLECTION_REPORT_SOURCE_FILE_FIELDS = ["source_label"] as const;
export const DEFLECTION_REPORT_SOURCE_FILE_REQUIRED_DATA = ["source_label"] as const;
export const DEFLECTION_REPORT_SOURCE_FILE_SNAPSHOT_SAFE_FIELDS = [] as const;
export const DEFLECTION_REPORT_SOURCE_FILE_HOSTED_CONSUMER_SAFE_FIELDS = [] as const;
export const DEFLECTION_REPORT_SEO_TARGETS_FIELDS = ["phrases", "total_phrase_count", "displayed_phrase_count", "omitted_phrase_count", "limit"] as const;
export const DEFLECTION_REPORT_SEO_TARGETS_REQUIRED_DATA = ["phrases", "total_phrase_count", "displayed_phrase_count", "omitted_phrase_count", "limit"] as const;
export const DEFLECTION_REPORT_SEO_TARGETS_SNAPSHOT_SAFE_FIELDS = [] as const;
export const DEFLECTION_REPORT_SEO_TARGETS_HOSTED_CONSUMER_SAFE_FIELDS = ["phrases", "total_phrase_count", "displayed_phrase_count", "omitted_phrase_count", "limit"] as const;
export const DEFLECTION_REPORT_RANKED_QUESTIONS_FIELDS = ["rows"] as const;
export const DEFLECTION_REPORT_RANKED_QUESTIONS_REQUIRED_DATA = ["rows"] as const;
export const DEFLECTION_REPORT_RANKED_QUESTIONS_SNAPSHOT_SAFE_FIELDS = ["rows.rank", "rows.question", "rows.ticket_count", "rows.weighted_frequency", "rows.customer_wording"] as const;
export const DEFLECTION_REPORT_RANKED_QUESTIONS_HOSTED_CONSUMER_SAFE_FIELDS = ["rows"] as const;
export const DEFLECTION_REPORT_RANKED_QUESTIONS_ROWS_HOSTED_CONSUMER_SAFE_FIELDS = ["rank", "question", "ticket_count", "weighted_frequency", "customer_wording", "estimated_support_cost", "opportunity_score", "answer_status", "source_proof"] as const;
export const DEFLECTION_REPORT_RANKED_QUESTIONS_ROWS_FIELDS = ["rank", "question", "ticket_count", "weighted_frequency", "customer_wording", "estimated_support_cost", "opportunity_score", "answer_status", "source_proof"] as const;
export const DEFLECTION_REPORT_PRIORITY_FIX_QUEUE_FIELDS = ["items", "status_counts", "result_page_limit", "pdf_limit", "backlog_limit", "support_cost_basis"] as const;
export const DEFLECTION_REPORT_PRIORITY_FIX_QUEUE_REQUIRED_DATA = ["items", "status_counts", "result_page_limit", "pdf_limit", "backlog_limit", "support_cost_basis"] as const;
export const DEFLECTION_REPORT_PRIORITY_FIX_QUEUE_SNAPSHOT_SAFE_FIELDS = [] as const;
export const DEFLECTION_REPORT_PRIORITY_FIX_QUEUE_HOSTED_CONSUMER_SAFE_FIELDS = ["items", "status_counts", "result_page_limit", "pdf_limit", "backlog_limit", "support_cost_basis"] as const;
export const DEFLECTION_REPORT_PRIORITY_FIX_QUEUE_SUPPORT_COST_BASIS_HOSTED_CONSUMER_SAFE_FIELDS = ["status"] as const;
export const DEFLECTION_REPORT_PRIORITY_FIX_QUEUE_ITEMS_HOSTED_CONSUMER_SAFE_FIELDS = ["rank", "question", "status", "owner_lane", "evidence_tier", "routing_signals", "confidence", "recommended_action", "ticket_count", "estimated_support_cost", "priority_score", "priority_drivers", "csat_signal"] as const;
export const DEFLECTION_REPORT_PRIORITY_FIX_QUEUE_ITEMS_CSAT_SIGNAL_HOSTED_CONSUMER_SAFE_FIELDS = ["status", "csat_present_count", "negative_csat_ticket_count", "numeric_average"] as const;
export const DEFLECTION_REPORT_PRIORITY_FIX_QUEUE_ITEMS_ROUTING_SIGNALS_HOSTED_CONSUMER_SAFE_FIELDS = ["group", "tags", "product_area", "custom_product_area"] as const;
export const DEFLECTION_REPORT_PRIORITY_FIX_QUEUE_ITEMS_TOP_EVIDENCE_HOSTED_CONSUMER_SAFE_FIELDS = [] as const;
export const DEFLECTION_REPORT_PRIORITY_FIX_QUEUE_ITEMS_FIELDS = ["rank", "repeat_key", "cluster_id", "identity_basis", "identity_confidence", "question", "status", "owner_lane", "evidence_tier", "routing_signals", "fix_type", "csat_signal", "confidence", "priority_score", "priority_drivers", "recommended_title", "recommended_action", "representative_phrasing", "ticket_count", "estimated_support_cost", "support_cost_formula", "support_cost_source", "opportunity_score", "top_evidence"] as const;
export const DEFLECTION_REPORT_TOP_UNRESOLVED_REPEATS_FIELDS = ["items", "top_item_count", "result_page_limit", "pdf_limit", "support_cost_basis"] as const;
export const DEFLECTION_REPORT_TOP_UNRESOLVED_REPEATS_REQUIRED_DATA = ["items", "top_item_count", "result_page_limit", "pdf_limit", "support_cost_basis"] as const;
export const DEFLECTION_REPORT_TOP_UNRESOLVED_REPEATS_SNAPSHOT_SAFE_FIELDS = ["items.rank", "items.question", "items.ticket_count"] as const;
export const DEFLECTION_REPORT_TOP_UNRESOLVED_REPEATS_HOSTED_CONSUMER_SAFE_FIELDS = ["items", "top_item_count", "support_cost_basis"] as const;
export const DEFLECTION_REPORT_TOP_UNRESOLVED_REPEATS_SUPPORT_COST_BASIS_HOSTED_CONSUMER_SAFE_FIELDS = ["status"] as const;
export const DEFLECTION_REPORT_TOP_UNRESOLVED_REPEATS_ITEMS_HOSTED_CONSUMER_SAFE_FIELDS = ["rank", "question", "status", "owner_lane", "evidence_tier", "routing_signals", "confidence", "recommended_action", "ticket_count", "estimated_support_cost", "priority_score", "priority_drivers", "csat_signal"] as const;
export const DEFLECTION_REPORT_TOP_UNRESOLVED_REPEATS_ITEMS_CSAT_SIGNAL_HOSTED_CONSUMER_SAFE_FIELDS = ["status", "csat_present_count", "negative_csat_ticket_count", "numeric_average"] as const;
export const DEFLECTION_REPORT_TOP_UNRESOLVED_REPEATS_ITEMS_ROUTING_SIGNALS_HOSTED_CONSUMER_SAFE_FIELDS = ["group", "tags", "product_area", "custom_product_area"] as const;
export const DEFLECTION_REPORT_TOP_UNRESOLVED_REPEATS_ITEMS_TOP_EVIDENCE_HOSTED_CONSUMER_SAFE_FIELDS = [] as const;
export const DEFLECTION_REPORT_TOP_UNRESOLVED_REPEATS_ITEMS_FIELDS = ["rank", "repeat_key", "cluster_id", "identity_basis", "identity_confidence", "question", "status", "owner_lane", "evidence_tier", "routing_signals", "fix_type", "csat_signal", "confidence", "priority_score", "priority_drivers", "recommended_title", "recommended_action", "representative_phrasing", "ticket_count", "estimated_support_cost", "support_cost_formula", "support_cost_source", "opportunity_score", "top_evidence"] as const;
export const DEFLECTION_REPORT_DRAFTED_RESOLUTIONS_FIELDS = ["items", "top_item_count", "result_page_limit", "pdf_limit"] as const;
export const DEFLECTION_REPORT_DRAFTED_RESOLUTIONS_REQUIRED_DATA = ["items", "top_item_count", "result_page_limit", "pdf_limit"] as const;
export const DEFLECTION_REPORT_DRAFTED_RESOLUTIONS_SNAPSHOT_SAFE_FIELDS = [] as const;
export const DEFLECTION_REPORT_DRAFTED_RESOLUTIONS_HOSTED_CONSUMER_SAFE_FIELDS = ["items", "top_item_count"] as const;
export const DEFLECTION_REPORT_DRAFTED_RESOLUTIONS_ITEMS_HOSTED_CONSUMER_SAFE_FIELDS = ["rank", "question", "status", "owner_lane", "evidence_tier", "routing_signals", "confidence", "recommended_action", "ticket_count", "estimated_support_cost", "priority_score", "priority_drivers", "csat_signal"] as const;
export const DEFLECTION_REPORT_DRAFTED_RESOLUTIONS_ITEMS_CSAT_SIGNAL_HOSTED_CONSUMER_SAFE_FIELDS = ["status", "csat_present_count", "negative_csat_ticket_count", "numeric_average"] as const;
export const DEFLECTION_REPORT_DRAFTED_RESOLUTIONS_ITEMS_ROUTING_SIGNALS_HOSTED_CONSUMER_SAFE_FIELDS = ["group", "tags", "product_area", "custom_product_area"] as const;
export const DEFLECTION_REPORT_DRAFTED_RESOLUTIONS_ITEMS_TOP_EVIDENCE_HOSTED_CONSUMER_SAFE_FIELDS = [] as const;
export const DEFLECTION_REPORT_DRAFTED_RESOLUTIONS_ITEMS_FIELDS = ["rank", "repeat_key", "cluster_id", "identity_basis", "identity_confidence", "question", "status", "owner_lane", "evidence_tier", "routing_signals", "fix_type", "csat_signal", "confidence", "priority_score", "priority_drivers", "recommended_title", "recommended_action", "representative_phrasing", "ticket_count", "estimated_support_cost", "support_cost_formula", "support_cost_source", "opportunity_score", "top_evidence"] as const;
export const DEFLECTION_REPORT_ALREADY_COVERED_STILL_RECURRING_FIELDS = ["items", "top_item_count", "result_page_limit", "pdf_limit"] as const;
export const DEFLECTION_REPORT_ALREADY_COVERED_STILL_RECURRING_REQUIRED_DATA = ["items", "top_item_count", "result_page_limit", "pdf_limit"] as const;
export const DEFLECTION_REPORT_ALREADY_COVERED_STILL_RECURRING_SNAPSHOT_SAFE_FIELDS = [] as const;
export const DEFLECTION_REPORT_ALREADY_COVERED_STILL_RECURRING_HOSTED_CONSUMER_SAFE_FIELDS = ["items", "top_item_count"] as const;
export const DEFLECTION_REPORT_ALREADY_COVERED_STILL_RECURRING_ITEMS_HOSTED_CONSUMER_SAFE_FIELDS = ["rank", "question", "status", "owner_lane", "evidence_tier", "routing_signals", "confidence", "recommended_action", "ticket_count", "estimated_support_cost", "priority_score", "priority_drivers", "csat_signal"] as const;
export const DEFLECTION_REPORT_ALREADY_COVERED_STILL_RECURRING_ITEMS_CSAT_SIGNAL_HOSTED_CONSUMER_SAFE_FIELDS = ["status", "csat_present_count", "negative_csat_ticket_count", "numeric_average"] as const;
export const DEFLECTION_REPORT_ALREADY_COVERED_STILL_RECURRING_ITEMS_ROUTING_SIGNALS_HOSTED_CONSUMER_SAFE_FIELDS = ["group", "tags", "product_area", "custom_product_area"] as const;
export const DEFLECTION_REPORT_ALREADY_COVERED_STILL_RECURRING_ITEMS_TOP_EVIDENCE_HOSTED_CONSUMER_SAFE_FIELDS = [] as const;
export const DEFLECTION_REPORT_ALREADY_COVERED_STILL_RECURRING_ITEMS_FIELDS = ["rank", "repeat_key", "cluster_id", "identity_basis", "identity_confidence", "question", "status", "owner_lane", "evidence_tier", "routing_signals", "fix_type", "csat_signal", "confidence", "priority_score", "priority_drivers", "recommended_title", "recommended_action", "representative_phrasing", "ticket_count", "estimated_support_cost", "support_cost_formula", "support_cost_source", "opportunity_score", "top_evidence"] as const;
export const DEFLECTION_REPORT_BACKLOG_TABLE_FIELDS = ["items", "total_item_count", "default_limit"] as const;
export const DEFLECTION_REPORT_BACKLOG_TABLE_REQUIRED_DATA = ["items", "total_item_count", "default_limit"] as const;
export const DEFLECTION_REPORT_BACKLOG_TABLE_SNAPSHOT_SAFE_FIELDS = [] as const;
export const DEFLECTION_REPORT_BACKLOG_TABLE_HOSTED_CONSUMER_SAFE_FIELDS = ["items", "total_item_count", "default_limit"] as const;
export const DEFLECTION_REPORT_BACKLOG_TABLE_ITEMS_HOSTED_CONSUMER_SAFE_FIELDS = ["rank", "question", "status", "owner_lane", "evidence_tier", "routing_signals", "confidence", "recommended_action", "ticket_count", "estimated_support_cost", "priority_score", "priority_drivers", "csat_signal"] as const;
export const DEFLECTION_REPORT_BACKLOG_TABLE_ITEMS_CSAT_SIGNAL_HOSTED_CONSUMER_SAFE_FIELDS = ["status", "csat_present_count", "negative_csat_ticket_count", "numeric_average"] as const;
export const DEFLECTION_REPORT_BACKLOG_TABLE_ITEMS_ROUTING_SIGNALS_HOSTED_CONSUMER_SAFE_FIELDS = ["group", "tags", "product_area", "custom_product_area"] as const;
export const DEFLECTION_REPORT_BACKLOG_TABLE_ITEMS_TOP_EVIDENCE_HOSTED_CONSUMER_SAFE_FIELDS = [] as const;
export const DEFLECTION_REPORT_BACKLOG_TABLE_ITEMS_FIELDS = ["rank", "repeat_key", "cluster_id", "identity_basis", "identity_confidence", "question", "status", "owner_lane", "evidence_tier", "routing_signals", "fix_type", "csat_signal", "confidence", "priority_score", "priority_drivers", "recommended_title", "recommended_action", "representative_phrasing", "ticket_count", "estimated_support_cost", "support_cost_formula", "support_cost_source", "opportunity_score", "top_evidence"] as const;
export const DEFLECTION_REPORT_OUTCOME_DIAGNOSTICS_FIELDS = ["outcome_diagnostic_ticket_count", "outcome_risk_ticket_count", "reopened_ticket_count", "negative_csat_ticket_count", "rows"] as const;
export const DEFLECTION_REPORT_OUTCOME_DIAGNOSTICS_REQUIRED_DATA = ["outcome_diagnostic_ticket_count", "outcome_risk_ticket_count", "reopened_ticket_count", "negative_csat_ticket_count", "rows"] as const;
export const DEFLECTION_REPORT_OUTCOME_DIAGNOSTICS_SNAPSHOT_SAFE_FIELDS = [] as const;
export const DEFLECTION_REPORT_OUTCOME_DIAGNOSTICS_HOSTED_CONSUMER_SAFE_FIELDS = ["outcome_diagnostic_ticket_count", "outcome_risk_ticket_count", "reopened_ticket_count", "negative_csat_ticket_count", "rows"] as const;
export const DEFLECTION_REPORT_OUTCOME_DIAGNOSTICS_ROWS_HOSTED_CONSUMER_SAFE_FIELDS = ["question", "status_mix", "reopened_ticket_count", "negative_csat_ticket_count", "guidance"] as const;
export const DEFLECTION_REPORT_OUTCOME_DIAGNOSTICS_ROWS_FIELDS = ["question", "status_mix", "reopened_ticket_count", "negative_csat_ticket_count", "guidance"] as const;
export const DEFLECTION_REPORT_SUPPRESSED_REPEAT_REVIEW_QUEUE_FIELDS = ["items", "total_item_count", "default_limit", "reason_counts"] as const;
export const DEFLECTION_REPORT_SUPPRESSED_REPEAT_REVIEW_QUEUE_REQUIRED_DATA = ["items", "total_item_count", "default_limit", "reason_counts"] as const;
export const DEFLECTION_REPORT_SUPPRESSED_REPEAT_REVIEW_QUEUE_SNAPSHOT_SAFE_FIELDS = [] as const;
export const DEFLECTION_REPORT_SUPPRESSED_REPEAT_REVIEW_QUEUE_HOSTED_CONSUMER_SAFE_FIELDS = ["items", "total_item_count", "default_limit", "reason_counts"] as const;
export const DEFLECTION_REPORT_SUPPRESSED_REPEAT_REVIEW_QUEUE_ITEMS_HOSTED_CONSUMER_SAFE_FIELDS = ["rank", "question", "status", "owner_lane", "evidence_tier", "routing_signals", "confidence", "recommended_action", "ticket_count", "estimated_support_cost", "priority_score", "priority_drivers", "csat_signal", "review_key", "suppression_reason", "suppression_reason_label"] as const;
export const DEFLECTION_REPORT_SUPPRESSED_REPEAT_REVIEW_QUEUE_ITEMS_CSAT_SIGNAL_HOSTED_CONSUMER_SAFE_FIELDS = ["status", "csat_present_count", "negative_csat_ticket_count", "numeric_average"] as const;
export const DEFLECTION_REPORT_SUPPRESSED_REPEAT_REVIEW_QUEUE_ITEMS_ROUTING_SIGNALS_HOSTED_CONSUMER_SAFE_FIELDS = ["group", "tags", "product_area", "custom_product_area"] as const;
export const DEFLECTION_REPORT_SUPPRESSED_REPEAT_REVIEW_QUEUE_ITEMS_TOP_EVIDENCE_HOSTED_CONSUMER_SAFE_FIELDS = [] as const;
export const DEFLECTION_REPORT_SUPPRESSED_REPEAT_REVIEW_QUEUE_ITEMS_FIELDS = ["rank", "repeat_key", "cluster_id", "identity_basis", "identity_confidence", "question", "status", "owner_lane", "evidence_tier", "routing_signals", "fix_type", "csat_signal", "confidence", "priority_score", "priority_drivers", "recommended_title", "recommended_action", "representative_phrasing", "ticket_count", "estimated_support_cost", "support_cost_formula", "support_cost_source", "opportunity_score", "top_evidence", "review_key", "suppression_reason", "suppression_reason_label"] as const;
export const DEFLECTION_REPORT_QUESTION_DETAILS_FIELDS = ["rows"] as const;
export const DEFLECTION_REPORT_QUESTION_DETAILS_REQUIRED_DATA = ["rows"] as const;
export const DEFLECTION_REPORT_QUESTION_DETAILS_SNAPSHOT_SAFE_FIELDS = ["rows.rank", "rows.question", "rows.answer_evidence_status", "rows.resolution_evidence_scope", "rows.weighted_frequency", "rows.source_count"] as const;
export const DEFLECTION_REPORT_QUESTION_DETAILS_HOSTED_CONSUMER_SAFE_FIELDS = ["rows"] as const;
export const DEFLECTION_REPORT_QUESTION_DETAILS_ROWS_HOSTED_CONSUMER_SAFE_FIELDS = ["rank", "question", "customer_wording", "topic", "ticket_count", "weighted_frequency", "source_count", "estimated_support_cost", "answer_status", "answer_evidence_status", "resolution_evidence_scope", "answer_linkage", "answer", "steps", "term_mappings"] as const;
export const DEFLECTION_REPORT_QUESTION_DETAILS_ROWS_TERM_MAPPINGS_HOSTED_CONSUMER_SAFE_FIELDS = ["customer_term", "documentation_term", "suggestion", "source_id_count"] as const;
export const DEFLECTION_REPORT_QUESTION_DETAILS_ROWS_FIELDS = ["rank", "question", "customer_wording", "topic", "ticket_count", "weighted_frequency", "source_count", "estimated_support_cost", "answer_status", "answer_evidence_status", "resolution_evidence_scope", "answer_linkage", "answer", "steps", "term_mappings", "source_ids", "evidence_quotes", "outcome_diagnostics"] as const;
export const DEFLECTION_REPORT_COMPLETE_EVIDENCE_FIELDS = ["question_count", "evidence_row_count", "source_id_count", "surfaces"] as const;
export const DEFLECTION_REPORT_COMPLETE_EVIDENCE_REQUIRED_DATA = ["question_count", "evidence_row_count", "source_id_count", "surfaces"] as const;
export const DEFLECTION_REPORT_COMPLETE_EVIDENCE_SNAPSHOT_SAFE_FIELDS = [] as const;
export const DEFLECTION_REPORT_COMPLETE_EVIDENCE_HOSTED_CONSUMER_SAFE_FIELDS = [] as const;
export const DEFLECTION_REPORT_HOSTED_FIELD_SHAPES = {
    "already_covered_still_recurring": {
        "items": "object_array",
        "top_item_count": "scalar",
    },
    "already_covered_still_recurring.items": {
        "rank": "scalar",
        "question": "scalar",
        "status": "scalar",
        "owner_lane": "scalar",
        "evidence_tier": "scalar",
        "routing_signals": "object",
        "confidence": "scalar",
        "recommended_action": "scalar",
        "ticket_count": "scalar",
        "estimated_support_cost": "scalar",
        "priority_score": "scalar",
        "priority_drivers": "scalar_array",
        "csat_signal": "object",
    },
    "already_covered_still_recurring.items.csat_signal": {
        "status": "scalar",
        "csat_present_count": "scalar",
        "negative_csat_ticket_count": "scalar",
        "numeric_average": "scalar",
    },
    "already_covered_still_recurring.items.routing_signals": {
        "group": "scalar_array",
        "tags": "scalar_array",
        "product_area": "scalar_array",
        "custom_product_area": "scalar_array",
    },
    "backlog_table": {
        "items": "object_array",
        "total_item_count": "scalar",
        "default_limit": "scalar",
    },
    "backlog_table.items": {
        "rank": "scalar",
        "question": "scalar",
        "status": "scalar",
        "owner_lane": "scalar",
        "evidence_tier": "scalar",
        "routing_signals": "object",
        "confidence": "scalar",
        "recommended_action": "scalar",
        "ticket_count": "scalar",
        "estimated_support_cost": "scalar",
        "priority_score": "scalar",
        "priority_drivers": "scalar_array",
        "csat_signal": "object",
    },
    "backlog_table.items.csat_signal": {
        "status": "scalar",
        "csat_present_count": "scalar",
        "negative_csat_ticket_count": "scalar",
        "numeric_average": "scalar",
    },
    "backlog_table.items.routing_signals": {
        "group": "scalar_array",
        "tags": "scalar_array",
        "product_area": "scalar_array",
        "custom_product_area": "scalar_array",
    },
    "drafted_resolutions": {
        "items": "object_array",
        "top_item_count": "scalar",
    },
    "drafted_resolutions.items": {
        "rank": "scalar",
        "question": "scalar",
        "status": "scalar",
        "owner_lane": "scalar",
        "evidence_tier": "scalar",
        "routing_signals": "object",
        "confidence": "scalar",
        "recommended_action": "scalar",
        "ticket_count": "scalar",
        "estimated_support_cost": "scalar",
        "priority_score": "scalar",
        "priority_drivers": "scalar_array",
        "csat_signal": "object",
    },
    "drafted_resolutions.items.csat_signal": {
        "status": "scalar",
        "csat_present_count": "scalar",
        "negative_csat_ticket_count": "scalar",
        "numeric_average": "scalar",
    },
    "drafted_resolutions.items.routing_signals": {
        "group": "scalar_array",
        "tags": "scalar_array",
        "product_area": "scalar_array",
        "custom_product_area": "scalar_array",
    },
    "outcome_diagnostics": {
        "outcome_diagnostic_ticket_count": "scalar",
        "outcome_risk_ticket_count": "scalar",
        "reopened_ticket_count": "scalar",
        "negative_csat_ticket_count": "scalar",
        "rows": "object_array",
    },
    "outcome_diagnostics.rows": {
        "question": "scalar",
        "status_mix": "scalar",
        "reopened_ticket_count": "scalar",
        "negative_csat_ticket_count": "scalar",
        "guidance": "scalar",
    },
    "priority_fix_queue": {
        "items": "object_array",
        "status_counts": "record",
        "result_page_limit": "scalar",
        "pdf_limit": "scalar",
        "backlog_limit": "scalar",
        "support_cost_basis": "object",
    },
    "priority_fix_queue.items": {
        "rank": "scalar",
        "question": "scalar",
        "status": "scalar",
        "owner_lane": "scalar",
        "evidence_tier": "scalar",
        "routing_signals": "object",
        "confidence": "scalar",
        "recommended_action": "scalar",
        "ticket_count": "scalar",
        "estimated_support_cost": "scalar",
        "priority_score": "scalar",
        "priority_drivers": "scalar_array",
        "csat_signal": "object",
    },
    "priority_fix_queue.items.csat_signal": {
        "status": "scalar",
        "csat_present_count": "scalar",
        "negative_csat_ticket_count": "scalar",
        "numeric_average": "scalar",
    },
    "priority_fix_queue.items.routing_signals": {
        "group": "scalar_array",
        "tags": "scalar_array",
        "product_area": "scalar_array",
        "custom_product_area": "scalar_array",
    },
    "priority_fix_queue.support_cost_basis": {
        "status": "scalar",
    },
    "question_details": {
        "rows": "object_array",
    },
    "question_details.rows": {
        "rank": "scalar",
        "question": "scalar",
        "customer_wording": "scalar",
        "topic": "scalar",
        "ticket_count": "scalar",
        "weighted_frequency": "scalar",
        "source_count": "scalar",
        "estimated_support_cost": "scalar",
        "answer_status": "scalar",
        "answer_evidence_status": "scalar",
        "resolution_evidence_scope": "scalar",
        "answer_linkage": "scalar",
        "answer": "scalar",
        "steps": "scalar_array",
        "term_mappings": "object_array",
    },
    "question_details.rows.term_mappings": {
        "customer_term": "scalar",
        "documentation_term": "scalar",
        "suggestion": "scalar",
        "source_id_count": "scalar",
    },
    "ranked_questions": {
        "rows": "object_array",
    },
    "ranked_questions.rows": {
        "rank": "scalar",
        "question": "scalar",
        "ticket_count": "scalar",
        "weighted_frequency": "scalar",
        "customer_wording": "scalar",
        "estimated_support_cost": "scalar",
        "opportunity_score": "scalar",
        "answer_status": "scalar",
        "source_proof": "scalar",
    },
    "seo_targets": {
        "phrases": "scalar_array",
        "total_phrase_count": "scalar",
        "displayed_phrase_count": "scalar",
        "omitted_phrase_count": "scalar",
        "limit": "scalar",
    },
    "support_tax": {
        "repeat_ticket_count": "scalar",
        "non_repeat_ticket_count": "scalar",
        "generated_question_count": "scalar",
        "assisted_contact_cost": "scalar",
        "estimated_support_cost": "scalar",
        "source_date_window": "object",
        "drafted_answer_count": "scalar",
        "no_proven_answer_count": "scalar",
        "ticket_source_count": "scalar",
        "annualized_support_cost": "scalar",
        "annualized_run_rate_support_cost": "scalar",
    },
    "support_tax.source_date_window": {
        "source_date_start": "scalar",
        "source_date_end": "scalar",
        "source_window_days": "scalar",
    },
    "suppressed_repeat_review_queue": {
        "items": "object_array",
        "total_item_count": "scalar",
        "default_limit": "scalar",
        "reason_counts": "record",
    },
    "suppressed_repeat_review_queue.items": {
        "rank": "scalar",
        "question": "scalar",
        "status": "scalar",
        "owner_lane": "scalar",
        "evidence_tier": "scalar",
        "routing_signals": "object",
        "confidence": "scalar",
        "recommended_action": "scalar",
        "ticket_count": "scalar",
        "estimated_support_cost": "scalar",
        "priority_score": "scalar",
        "priority_drivers": "scalar_array",
        "csat_signal": "object",
        "review_key": "scalar",
        "suppression_reason": "scalar",
        "suppression_reason_label": "scalar",
    },
    "suppressed_repeat_review_queue.items.csat_signal": {
        "status": "scalar",
        "csat_present_count": "scalar",
        "negative_csat_ticket_count": "scalar",
        "numeric_average": "scalar",
    },
    "suppressed_repeat_review_queue.items.routing_signals": {
        "group": "scalar_array",
        "tags": "scalar_array",
        "product_area": "scalar_array",
        "custom_product_area": "scalar_array",
    },
    "top_unresolved_repeats": {
        "items": "object_array",
        "top_item_count": "scalar",
        "support_cost_basis": "object",
    },
    "top_unresolved_repeats.items": {
        "rank": "scalar",
        "question": "scalar",
        "status": "scalar",
        "owner_lane": "scalar",
        "evidence_tier": "scalar",
        "routing_signals": "object",
        "confidence": "scalar",
        "recommended_action": "scalar",
        "ticket_count": "scalar",
        "estimated_support_cost": "scalar",
        "priority_score": "scalar",
        "priority_drivers": "scalar_array",
        "csat_signal": "object",
    },
    "top_unresolved_repeats.items.csat_signal": {
        "status": "scalar",
        "csat_present_count": "scalar",
        "negative_csat_ticket_count": "scalar",
        "numeric_average": "scalar",
    },
    "top_unresolved_repeats.items.routing_signals": {
        "group": "scalar_array",
        "tags": "scalar_array",
        "product_area": "scalar_array",
        "custom_product_area": "scalar_array",
    },
    "top_unresolved_repeats.support_cost_basis": {
        "status": "scalar",
    },
} as const;
export type DeflectionReportSourceDateWindow = {
    source_date_start: string | null;
    source_date_end: string | null;
    source_window_days: number | null;
};
export type DeflectionReportTermMapping = {
    customer_term: string;
    documentation_term: string;
    suggestion: string;
    source_id_count: number;
};
export type DeflectionReportQuestionOutcomeDiagnostics = {
    ticket_status_summary?: Record<string, number>;
    diagnostic_ticket_count?: number;
    outcome_risk_ticket_count?: number;
    reopened_ticket_count?: number;
    negative_csat_ticket_count?: number;
    csat_present_count?: number;
    csat_score_average?: number | null;
};
export type DeflectionReportSupportTaxSourceDateWindow = {
    source_date_start: string | null;
    source_date_end: string | null;
    source_window_days: number | null;
};
export type DeflectionReportSupportTaxData = {
    repeat_ticket_count: number;
    non_repeat_ticket_count: number;
    generated_question_count: number;
    assisted_contact_cost: number;
    estimated_support_cost: number;
    source_date_window: DeflectionReportSupportTaxSourceDateWindow | null;
    drafted_answer_count: number;
    no_proven_answer_count: number;
    ticket_source_count: number;
    annualized_support_cost?: number;
    annualized_run_rate_support_cost?: number;
};
export type DeflectionReportSupportTaxSection = {
    id: "support_tax";
    title: string;
    priority: number;
    surfaces: string[];
    default_limit: number | null;
    required_data: string[];
    snapshot_safe_fields: string[];
    data: DeflectionReportSupportTaxData;
};
export type DeflectionReportSourceFileData = {
    source_label: string;
};
export type DeflectionReportSourceFileSection = {
    id: "source_file";
    title: string;
    priority: number;
    surfaces: string[];
    default_limit: number | null;
    required_data: string[];
    snapshot_safe_fields: string[];
    data: DeflectionReportSourceFileData;
};
export type DeflectionReportSeoTargetsData = {
    phrases: string[];
    total_phrase_count: number;
    displayed_phrase_count: number;
    omitted_phrase_count: number;
    limit: number;
};
export type DeflectionReportSeoTargetsSection = {
    id: "seo_targets";
    title: string;
    priority: number;
    surfaces: string[];
    default_limit: number | null;
    required_data: string[];
    snapshot_safe_fields: string[];
    data: DeflectionReportSeoTargetsData;
};
export type DeflectionReportRankedQuestionsRow = {
    rank: number;
    question: string;
    ticket_count: number;
    weighted_frequency: number;
    customer_wording: string;
    estimated_support_cost: number;
    opportunity_score: number;
    answer_status: string;
    source_proof: string;
};
export type DeflectionReportRankedQuestionsData = {
    rows: DeflectionReportRankedQuestionsRow[];
};
export type DeflectionReportRankedQuestionsSection = {
    id: "ranked_questions";
    title: string;
    priority: number;
    surfaces: string[];
    default_limit: number | null;
    required_data: string[];
    snapshot_safe_fields: string[];
    data: DeflectionReportRankedQuestionsData;
};
export type DeflectionReportPriorityFixQueueSupportCostBasis = {
    status: string;
    assisted_contact_cost: number;
    formula: string;
    source: string;
};
export type DeflectionReportPriorityFixQueueCsatSignal = {
    status: string;
    csat_present_count: number;
    negative_csat_ticket_count: number;
    numeric_average: number | null;
};
export type DeflectionReportPriorityFixQueueRoutingSignals = {
    group: string[];
    assignee: string[];
    tags: string[];
    brand: string[];
    organization: string[];
    product_area: string[];
    custom_product_area: string[];
};
export type DeflectionReportPriorityFixQueueTopEvidence = {
    source_id: string;
    evidence_quote: string;
};
export type DeflectionReportPriorityFixQueueItem = {
    rank: number;
    repeat_key: string;
    cluster_id: string;
    identity_basis: string;
    identity_confidence: string;
    question: string;
    status: string;
    owner_lane: string;
    evidence_tier?: string;
    routing_signals?: DeflectionReportPriorityFixQueueRoutingSignals;
    fix_type: string;
    csat_signal: DeflectionReportPriorityFixQueueCsatSignal;
    confidence: string;
    priority_score: number;
    priority_drivers: string[];
    recommended_title: string;
    recommended_action: string;
    representative_phrasing: string;
    ticket_count: number;
    estimated_support_cost: number;
    support_cost_formula: string;
    support_cost_source: string;
    opportunity_score: number;
    top_evidence: DeflectionReportPriorityFixQueueTopEvidence[];
};
export type DeflectionReportPriorityFixQueueData = {
    items: DeflectionReportPriorityFixQueueItem[];
    status_counts: Record<string, number>;
    result_page_limit: number;
    pdf_limit: number;
    backlog_limit: number;
    support_cost_basis: DeflectionReportPriorityFixQueueSupportCostBasis;
};
export type DeflectionReportPriorityFixQueueSection = {
    id: "priority_fix_queue";
    title: string;
    priority: number;
    surfaces: string[];
    default_limit: number | null;
    required_data: string[];
    snapshot_safe_fields: string[];
    data: DeflectionReportPriorityFixQueueData;
};
export type DeflectionReportTopUnresolvedRepeatsSupportCostBasis = {
    status: string;
    assisted_contact_cost: number;
    formula: string;
    source: string;
};
export type DeflectionReportTopUnresolvedRepeatsCsatSignal = {
    status: string;
    csat_present_count: number;
    negative_csat_ticket_count: number;
    numeric_average: number | null;
};
export type DeflectionReportTopUnresolvedRepeatsRoutingSignals = {
    group: string[];
    assignee: string[];
    tags: string[];
    brand: string[];
    organization: string[];
    product_area: string[];
    custom_product_area: string[];
};
export type DeflectionReportTopUnresolvedRepeatsTopEvidence = {
    source_id: string;
    evidence_quote: string;
};
export type DeflectionReportTopUnresolvedRepeatsItem = {
    rank: number;
    repeat_key: string;
    cluster_id: string;
    identity_basis: string;
    identity_confidence: string;
    question: string;
    status: string;
    owner_lane: string;
    evidence_tier?: string;
    routing_signals?: DeflectionReportTopUnresolvedRepeatsRoutingSignals;
    fix_type: string;
    csat_signal: DeflectionReportTopUnresolvedRepeatsCsatSignal;
    confidence: string;
    priority_score: number;
    priority_drivers: string[];
    recommended_title: string;
    recommended_action: string;
    representative_phrasing: string;
    ticket_count: number;
    estimated_support_cost: number;
    support_cost_formula: string;
    support_cost_source: string;
    opportunity_score: number;
    top_evidence: DeflectionReportTopUnresolvedRepeatsTopEvidence[];
};
export type DeflectionReportTopUnresolvedRepeatsData = {
    items: DeflectionReportTopUnresolvedRepeatsItem[];
    top_item_count: number;
    result_page_limit: number;
    pdf_limit: number;
    support_cost_basis: DeflectionReportTopUnresolvedRepeatsSupportCostBasis;
};
export type DeflectionReportTopUnresolvedRepeatsSection = {
    id: "top_unresolved_repeats";
    title: string;
    priority: number;
    surfaces: string[];
    default_limit: number | null;
    required_data: string[];
    snapshot_safe_fields: string[];
    data: DeflectionReportTopUnresolvedRepeatsData;
};
export type DeflectionReportDraftedResolutionsCsatSignal = {
    status: string;
    csat_present_count: number;
    negative_csat_ticket_count: number;
    numeric_average: number | null;
};
export type DeflectionReportDraftedResolutionsRoutingSignals = {
    group: string[];
    assignee: string[];
    tags: string[];
    brand: string[];
    organization: string[];
    product_area: string[];
    custom_product_area: string[];
};
export type DeflectionReportDraftedResolutionsTopEvidence = {
    source_id: string;
    evidence_quote: string;
};
export type DeflectionReportDraftedResolutionsItem = {
    rank: number;
    repeat_key: string;
    cluster_id: string;
    identity_basis: string;
    identity_confidence: string;
    question: string;
    status: string;
    owner_lane: string;
    evidence_tier?: string;
    routing_signals?: DeflectionReportDraftedResolutionsRoutingSignals;
    fix_type: string;
    csat_signal: DeflectionReportDraftedResolutionsCsatSignal;
    confidence: string;
    priority_score: number;
    priority_drivers: string[];
    recommended_title: string;
    recommended_action: string;
    representative_phrasing: string;
    ticket_count: number;
    estimated_support_cost: number;
    support_cost_formula: string;
    support_cost_source: string;
    opportunity_score: number;
    top_evidence: DeflectionReportDraftedResolutionsTopEvidence[];
};
export type DeflectionReportDraftedResolutionsData = {
    items: DeflectionReportDraftedResolutionsItem[];
    top_item_count: number;
    result_page_limit: number;
    pdf_limit: number;
};
export type DeflectionReportDraftedResolutionsSection = {
    id: "drafted_resolutions";
    title: string;
    priority: number;
    surfaces: string[];
    default_limit: number | null;
    required_data: string[];
    snapshot_safe_fields: string[];
    data: DeflectionReportDraftedResolutionsData;
};
export type DeflectionReportAlreadyCoveredStillRecurringCsatSignal = {
    status: string;
    csat_present_count: number;
    negative_csat_ticket_count: number;
    numeric_average: number | null;
};
export type DeflectionReportAlreadyCoveredStillRecurringRoutingSignals = {
    group: string[];
    assignee: string[];
    tags: string[];
    brand: string[];
    organization: string[];
    product_area: string[];
    custom_product_area: string[];
};
export type DeflectionReportAlreadyCoveredStillRecurringTopEvidence = {
    source_id: string;
    evidence_quote: string;
};
export type DeflectionReportAlreadyCoveredStillRecurringItem = {
    rank: number;
    repeat_key: string;
    cluster_id: string;
    identity_basis: string;
    identity_confidence: string;
    question: string;
    status: string;
    owner_lane: string;
    evidence_tier?: string;
    routing_signals?: DeflectionReportAlreadyCoveredStillRecurringRoutingSignals;
    fix_type: string;
    csat_signal: DeflectionReportAlreadyCoveredStillRecurringCsatSignal;
    confidence: string;
    priority_score: number;
    priority_drivers: string[];
    recommended_title: string;
    recommended_action: string;
    representative_phrasing: string;
    ticket_count: number;
    estimated_support_cost: number;
    support_cost_formula: string;
    support_cost_source: string;
    opportunity_score: number;
    top_evidence: DeflectionReportAlreadyCoveredStillRecurringTopEvidence[];
};
export type DeflectionReportAlreadyCoveredStillRecurringData = {
    items: DeflectionReportAlreadyCoveredStillRecurringItem[];
    top_item_count: number;
    result_page_limit: number;
    pdf_limit: number;
};
export type DeflectionReportAlreadyCoveredStillRecurringSection = {
    id: "already_covered_still_recurring";
    title: string;
    priority: number;
    surfaces: string[];
    default_limit: number | null;
    required_data: string[];
    snapshot_safe_fields: string[];
    data: DeflectionReportAlreadyCoveredStillRecurringData;
};
export type DeflectionReportBacklogTableCsatSignal = {
    status: string;
    csat_present_count: number;
    negative_csat_ticket_count: number;
    numeric_average: number | null;
};
export type DeflectionReportBacklogTableRoutingSignals = {
    group: string[];
    assignee: string[];
    tags: string[];
    brand: string[];
    organization: string[];
    product_area: string[];
    custom_product_area: string[];
};
export type DeflectionReportBacklogTableTopEvidence = {
    source_id: string;
    evidence_quote: string;
};
export type DeflectionReportBacklogTableItem = {
    rank: number;
    repeat_key: string;
    cluster_id: string;
    identity_basis: string;
    identity_confidence: string;
    question: string;
    status: string;
    owner_lane: string;
    evidence_tier?: string;
    routing_signals?: DeflectionReportBacklogTableRoutingSignals;
    fix_type: string;
    csat_signal: DeflectionReportBacklogTableCsatSignal;
    confidence: string;
    priority_score: number;
    priority_drivers: string[];
    recommended_title: string;
    recommended_action: string;
    representative_phrasing: string;
    ticket_count: number;
    estimated_support_cost: number;
    support_cost_formula: string;
    support_cost_source: string;
    opportunity_score: number;
    top_evidence: DeflectionReportBacklogTableTopEvidence[];
};
export type DeflectionReportBacklogTableData = {
    items: DeflectionReportBacklogTableItem[];
    total_item_count: number;
    default_limit: number;
};
export type DeflectionReportBacklogTableSection = {
    id: "backlog_table";
    title: string;
    priority: number;
    surfaces: string[];
    default_limit: number | null;
    required_data: string[];
    snapshot_safe_fields: string[];
    data: DeflectionReportBacklogTableData;
};
export type DeflectionReportOutcomeDiagnosticsRow = {
    question: string;
    status_mix: string;
    reopened_ticket_count: number;
    negative_csat_ticket_count: number;
    guidance: string;
};
export type DeflectionReportOutcomeDiagnosticsData = {
    outcome_diagnostic_ticket_count: number;
    outcome_risk_ticket_count: number;
    reopened_ticket_count: number;
    negative_csat_ticket_count: number;
    rows: DeflectionReportOutcomeDiagnosticsRow[];
};
export type DeflectionReportOutcomeDiagnosticsSection = {
    id: "outcome_diagnostics";
    title: string;
    priority: number;
    surfaces: string[];
    default_limit: number | null;
    required_data: string[];
    snapshot_safe_fields: string[];
    data: DeflectionReportOutcomeDiagnosticsData;
};
export type DeflectionReportSuppressedRepeatReviewQueueCsatSignal = {
    status: string;
    csat_present_count: number;
    negative_csat_ticket_count: number;
    numeric_average: number | null;
};
export type DeflectionReportSuppressedRepeatReviewQueueRoutingSignals = {
    group: string[];
    assignee: string[];
    tags: string[];
    brand: string[];
    organization: string[];
    product_area: string[];
    custom_product_area: string[];
};
export type DeflectionReportSuppressedRepeatReviewQueueTopEvidence = {
    source_id: string;
    evidence_quote: string;
};
export type DeflectionReportSuppressedRepeatReviewQueueItem = {
    rank: number;
    repeat_key: string;
    cluster_id: string;
    identity_basis: string;
    identity_confidence: string;
    question: string;
    status: string;
    owner_lane: string;
    evidence_tier: string;
    routing_signals: DeflectionReportSuppressedRepeatReviewQueueRoutingSignals;
    fix_type: string;
    csat_signal: DeflectionReportSuppressedRepeatReviewQueueCsatSignal;
    confidence: string;
    priority_score: number;
    priority_drivers: string[];
    recommended_title: string;
    recommended_action: string;
    representative_phrasing: string;
    ticket_count: number;
    estimated_support_cost: number;
    support_cost_formula: string;
    support_cost_source: string;
    opportunity_score: number;
    top_evidence: DeflectionReportSuppressedRepeatReviewQueueTopEvidence[];
    review_key: string;
    suppression_reason: string;
    suppression_reason_label: string;
};
export type DeflectionReportSuppressedRepeatReviewQueueData = {
    items: DeflectionReportSuppressedRepeatReviewQueueItem[];
    total_item_count: number;
    default_limit: number;
    reason_counts: Record<string, number>;
};
export type DeflectionReportSuppressedRepeatReviewQueueSection = {
    id: "suppressed_repeat_review_queue";
    title: string;
    priority: number;
    surfaces: string[];
    default_limit: number | null;
    required_data: string[];
    snapshot_safe_fields: string[];
    data: DeflectionReportSuppressedRepeatReviewQueueData;
};
export type DeflectionReportQuestionDetailsTermMappings = {
    customer_term: string;
    documentation_term: string;
    suggestion: string;
    source_id_count: number;
};
export type DeflectionReportQuestionDetailsRow = {
    rank: number;
    question: string;
    customer_wording: string;
    topic: string;
    ticket_count: number;
    weighted_frequency: number;
    source_count: number;
    estimated_support_cost: number;
    answer_status: string;
    answer_evidence_status: string;
    resolution_evidence_scope: string;
    answer_linkage: string;
    answer: string;
    steps: string[];
    term_mappings: DeflectionReportQuestionDetailsTermMappings[];
    source_ids: string[];
    evidence_quotes: string[];
    outcome_diagnostics: DeflectionReportQuestionOutcomeDiagnostics | null;
};
export type DeflectionReportQuestionDetailsData = {
    rows: DeflectionReportQuestionDetailsRow[];
};
export type DeflectionReportQuestionDetailsSection = {
    id: "question_details";
    title: string;
    priority: number;
    surfaces: string[];
    default_limit: number | null;
    required_data: string[];
    snapshot_safe_fields: string[];
    data: DeflectionReportQuestionDetailsData;
};
export type DeflectionReportCompleteEvidenceData = {
    question_count: number;
    evidence_row_count: number;
    source_id_count: number;
    surfaces: string[];
};
export type DeflectionReportCompleteEvidenceSection = {
    id: "complete_evidence";
    title: string;
    priority: number;
    surfaces: string[];
    default_limit: number | null;
    required_data: string[];
    snapshot_safe_fields: string[];
    data: DeflectionReportCompleteEvidenceData;
};
export type DeflectionReportSectionDataById = {
    support_tax: DeflectionReportSupportTaxData;
    source_file?: DeflectionReportSourceFileData;
    seo_targets: DeflectionReportSeoTargetsData;
    ranked_questions: DeflectionReportRankedQuestionsData;
    priority_fix_queue: DeflectionReportPriorityFixQueueData;
    top_unresolved_repeats: DeflectionReportTopUnresolvedRepeatsData;
    drafted_resolutions: DeflectionReportDraftedResolutionsData;
    already_covered_still_recurring: DeflectionReportAlreadyCoveredStillRecurringData;
    backlog_table: DeflectionReportBacklogTableData;
    outcome_diagnostics?: DeflectionReportOutcomeDiagnosticsData;
    suppressed_repeat_review_queue: DeflectionReportSuppressedRepeatReviewQueueData;
    question_details: DeflectionReportQuestionDetailsData;
    complete_evidence: DeflectionReportCompleteEvidenceData;
};
export type DeflectionReportSection = DeflectionReportSupportTaxSection | DeflectionReportSourceFileSection | DeflectionReportSeoTargetsSection | DeflectionReportRankedQuestionsSection | DeflectionReportPriorityFixQueueSection | DeflectionReportTopUnresolvedRepeatsSection | DeflectionReportDraftedResolutionsSection | DeflectionReportAlreadyCoveredStillRecurringSection | DeflectionReportBacklogTableSection | DeflectionReportOutcomeDiagnosticsSection | DeflectionReportSuppressedRepeatReviewQueueSection | DeflectionReportQuestionDetailsSection | DeflectionReportCompleteEvidenceSection;
export type DeflectionStructuredReport = {
    schema_version: typeof DEFLECTION_REPORT_MODEL_SCHEMA_VERSION;
    title: string;
    summary: Record<string, unknown>;
    sections: DeflectionReportSection[];
};

export const DEFLECTION_REPORT_HOSTED_FIELD_CONTRACT = {
  "already_covered_still_recurring": {
    "items": {
      "shape": "object_array",
      "required": true,
      "nullable": false
    },
    "top_item_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    }
  },
  "backlog_table": {
    "items": {
      "shape": "object_array",
      "required": true,
      "nullable": false
    },
    "total_item_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "default_limit": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    }
  },
  "drafted_resolutions": {
    "items": {
      "shape": "object_array",
      "required": true,
      "nullable": false
    },
    "top_item_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    }
  },
  "outcome_diagnostics": {
    "outcome_diagnostic_ticket_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "outcome_risk_ticket_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "reopened_ticket_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "negative_csat_ticket_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "rows": {
      "shape": "object_array",
      "required": true,
      "nullable": false
    }
  },
  "priority_fix_queue": {
    "items": {
      "shape": "object_array",
      "required": true,
      "nullable": false
    },
    "status_counts": {
      "shape": "record",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "result_page_limit": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "pdf_limit": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "backlog_limit": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "support_cost_basis": {
      "shape": "object",
      "required": true,
      "nullable": false
    }
  },
  "question_details": {
    "rows": {
      "shape": "object_array",
      "required": true,
      "nullable": false
    }
  },
  "ranked_questions": {
    "rows": {
      "shape": "object_array",
      "required": true,
      "nullable": false
    }
  },
  "seo_targets": {
    "phrases": {
      "shape": "scalar_array",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "total_phrase_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "displayed_phrase_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "omitted_phrase_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "limit": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    }
  },
  "support_tax": {
    "repeat_ticket_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "non_repeat_ticket_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "generated_question_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "assisted_contact_cost": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "estimated_support_cost": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "source_date_window": {
      "shape": "object",
      "required": true,
      "nullable": true
    },
    "drafted_answer_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "no_proven_answer_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "ticket_source_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "annualized_support_cost": {
      "shape": "scalar",
      "required": false,
      "nullable": false,
      "value": "number"
    },
    "annualized_run_rate_support_cost": {
      "shape": "scalar",
      "required": false,
      "nullable": false,
      "value": "number"
    }
  },
  "suppressed_repeat_review_queue": {
    "items": {
      "shape": "object_array",
      "required": true,
      "nullable": false
    },
    "total_item_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "default_limit": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "reason_counts": {
      "shape": "record",
      "required": true,
      "nullable": false,
      "value": "number"
    }
  },
  "top_unresolved_repeats": {
    "items": {
      "shape": "object_array",
      "required": true,
      "nullable": false
    },
    "top_item_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "support_cost_basis": {
      "shape": "object",
      "required": true,
      "nullable": false
    }
  },
  "already_covered_still_recurring.items": {
    "rank": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "question": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "status": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "owner_lane": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "evidence_tier": {
      "shape": "scalar",
      "required": false,
      "nullable": false,
      "value": "string"
    },
    "routing_signals": {
      "shape": "object",
      "required": false,
      "nullable": false
    },
    "confidence": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "recommended_action": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "ticket_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "estimated_support_cost": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "priority_score": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "priority_drivers": {
      "shape": "scalar_array",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "csat_signal": {
      "shape": "object",
      "required": true,
      "nullable": false
    }
  },
  "backlog_table.items": {
    "rank": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "question": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "status": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "owner_lane": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "evidence_tier": {
      "shape": "scalar",
      "required": false,
      "nullable": false,
      "value": "string"
    },
    "routing_signals": {
      "shape": "object",
      "required": false,
      "nullable": false
    },
    "confidence": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "recommended_action": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "ticket_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "estimated_support_cost": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "priority_score": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "priority_drivers": {
      "shape": "scalar_array",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "csat_signal": {
      "shape": "object",
      "required": true,
      "nullable": false
    }
  },
  "drafted_resolutions.items": {
    "rank": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "question": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "status": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "owner_lane": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "evidence_tier": {
      "shape": "scalar",
      "required": false,
      "nullable": false,
      "value": "string"
    },
    "routing_signals": {
      "shape": "object",
      "required": false,
      "nullable": false
    },
    "confidence": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "recommended_action": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "ticket_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "estimated_support_cost": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "priority_score": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "priority_drivers": {
      "shape": "scalar_array",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "csat_signal": {
      "shape": "object",
      "required": true,
      "nullable": false
    }
  },
  "outcome_diagnostics.rows": {
    "question": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "status_mix": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "reopened_ticket_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "negative_csat_ticket_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "guidance": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    }
  },
  "priority_fix_queue.items": {
    "rank": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "question": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "status": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "owner_lane": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "evidence_tier": {
      "shape": "scalar",
      "required": false,
      "nullable": false,
      "value": "string"
    },
    "routing_signals": {
      "shape": "object",
      "required": false,
      "nullable": false
    },
    "confidence": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "recommended_action": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "ticket_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "estimated_support_cost": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "priority_score": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "priority_drivers": {
      "shape": "scalar_array",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "csat_signal": {
      "shape": "object",
      "required": true,
      "nullable": false
    }
  },
  "priority_fix_queue.support_cost_basis": {
    "status": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    }
  },
  "question_details.rows": {
    "rank": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "question": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "customer_wording": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "topic": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "ticket_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "weighted_frequency": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "source_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "estimated_support_cost": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "answer_status": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "answer_evidence_status": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "resolution_evidence_scope": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "answer_linkage": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "answer": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "steps": {
      "shape": "scalar_array",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "term_mappings": {
      "shape": "object_array",
      "required": true,
      "nullable": false
    }
  },
  "ranked_questions.rows": {
    "rank": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "question": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "ticket_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "weighted_frequency": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "customer_wording": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "estimated_support_cost": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "opportunity_score": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "answer_status": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "source_proof": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    }
  },
  "support_tax.source_date_window": {
    "source_date_start": {
      "shape": "scalar",
      "required": true,
      "nullable": true,
      "value": "string"
    },
    "source_date_end": {
      "shape": "scalar",
      "required": true,
      "nullable": true,
      "value": "string"
    },
    "source_window_days": {
      "shape": "scalar",
      "required": true,
      "nullable": true,
      "value": "number"
    }
  },
  "suppressed_repeat_review_queue.items": {
    "rank": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "question": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "status": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "owner_lane": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "evidence_tier": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "routing_signals": {
      "shape": "object",
      "required": true,
      "nullable": false
    },
    "confidence": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "recommended_action": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "ticket_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "estimated_support_cost": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "priority_score": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "priority_drivers": {
      "shape": "scalar_array",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "csat_signal": {
      "shape": "object",
      "required": true,
      "nullable": false
    },
    "review_key": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "suppression_reason": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "suppression_reason_label": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    }
  },
  "top_unresolved_repeats.items": {
    "rank": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "question": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "status": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "owner_lane": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "evidence_tier": {
      "shape": "scalar",
      "required": false,
      "nullable": false,
      "value": "string"
    },
    "routing_signals": {
      "shape": "object",
      "required": false,
      "nullable": false
    },
    "confidence": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "recommended_action": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "ticket_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "estimated_support_cost": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "priority_score": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "priority_drivers": {
      "shape": "scalar_array",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "csat_signal": {
      "shape": "object",
      "required": true,
      "nullable": false
    }
  },
  "top_unresolved_repeats.support_cost_basis": {
    "status": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    }
  },
  "already_covered_still_recurring.items.csat_signal": {
    "status": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "csat_present_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "negative_csat_ticket_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "numeric_average": {
      "shape": "scalar",
      "required": true,
      "nullable": true,
      "value": "number"
    }
  },
  "already_covered_still_recurring.items.routing_signals": {
    "group": {
      "shape": "scalar_array",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "tags": {
      "shape": "scalar_array",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "product_area": {
      "shape": "scalar_array",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "custom_product_area": {
      "shape": "scalar_array",
      "required": true,
      "nullable": false,
      "value": "string"
    }
  },
  "backlog_table.items.csat_signal": {
    "status": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "csat_present_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "negative_csat_ticket_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "numeric_average": {
      "shape": "scalar",
      "required": true,
      "nullable": true,
      "value": "number"
    }
  },
  "backlog_table.items.routing_signals": {
    "group": {
      "shape": "scalar_array",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "tags": {
      "shape": "scalar_array",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "product_area": {
      "shape": "scalar_array",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "custom_product_area": {
      "shape": "scalar_array",
      "required": true,
      "nullable": false,
      "value": "string"
    }
  },
  "drafted_resolutions.items.csat_signal": {
    "status": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "csat_present_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "negative_csat_ticket_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "numeric_average": {
      "shape": "scalar",
      "required": true,
      "nullable": true,
      "value": "number"
    }
  },
  "drafted_resolutions.items.routing_signals": {
    "group": {
      "shape": "scalar_array",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "tags": {
      "shape": "scalar_array",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "product_area": {
      "shape": "scalar_array",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "custom_product_area": {
      "shape": "scalar_array",
      "required": true,
      "nullable": false,
      "value": "string"
    }
  },
  "priority_fix_queue.items.csat_signal": {
    "status": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "csat_present_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "negative_csat_ticket_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "numeric_average": {
      "shape": "scalar",
      "required": true,
      "nullable": true,
      "value": "number"
    }
  },
  "priority_fix_queue.items.routing_signals": {
    "group": {
      "shape": "scalar_array",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "tags": {
      "shape": "scalar_array",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "product_area": {
      "shape": "scalar_array",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "custom_product_area": {
      "shape": "scalar_array",
      "required": true,
      "nullable": false,
      "value": "string"
    }
  },
  "question_details.rows.term_mappings": {
    "customer_term": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "documentation_term": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "suggestion": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "source_id_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    }
  },
  "suppressed_repeat_review_queue.items.csat_signal": {
    "status": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "csat_present_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "negative_csat_ticket_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "numeric_average": {
      "shape": "scalar",
      "required": true,
      "nullable": true,
      "value": "number"
    }
  },
  "suppressed_repeat_review_queue.items.routing_signals": {
    "group": {
      "shape": "scalar_array",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "tags": {
      "shape": "scalar_array",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "product_area": {
      "shape": "scalar_array",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "custom_product_area": {
      "shape": "scalar_array",
      "required": true,
      "nullable": false,
      "value": "string"
    }
  },
  "top_unresolved_repeats.items.csat_signal": {
    "status": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "csat_present_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "negative_csat_ticket_count": {
      "shape": "scalar",
      "required": true,
      "nullable": false,
      "value": "number"
    },
    "numeric_average": {
      "shape": "scalar",
      "required": true,
      "nullable": true,
      "value": "number"
    }
  },
  "top_unresolved_repeats.items.routing_signals": {
    "group": {
      "shape": "scalar_array",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "tags": {
      "shape": "scalar_array",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "product_area": {
      "shape": "scalar_array",
      "required": true,
      "nullable": false,
      "value": "string"
    },
    "custom_product_area": {
      "shape": "scalar_array",
      "required": true,
      "nullable": false,
      "value": "string"
    }
  }
} as const;
