/*
 * Generated by web/scripts/generate-deflection-snapshot-contract.mjs.
 * Source: ATLAS portfolio-ui/src/types/deflectionSnapshot.ts,
 * generated from the backend deflection report contract.
 * Do not edit by hand; run npm --prefix web run generate:deflection-snapshot-contract.
 */

export const DEFLECTION_SNAPSHOT_SCHEMA_VERSION = "deflection.v1" as const;

export const DEFLECTION_SNAPSHOT_TOP_LEVEL_FIELDS = ["summary", "top_questions", "locked_questions", "top_blind_spots", "teaser"] as const;

export const DEFLECTION_RESULT_PAGE_SNAPSHOT_FIELDS = ["summary", "top_questions", "top_blind_spots"] as const;

export const DEFLECTION_SNAPSHOT_SUMMARY_FIELDS = ["generated", "drafted_answer_count", "no_proven_answer_count", "support_ticket_resolution_evidence_present", "support_ticket_resolution_evidence_count", "repeat_ticket_count", "non_repeat_ticket_count", "source_date_start", "source_date_end", "source_window_days"] as const;

export const DEFLECTION_SNAPSHOT_SUMMARY_OPTIONAL_FIELDS = ["source_date_start", "source_date_end", "source_window_days"] as const;

export const DEFLECTION_SNAPSHOT_TOP_QUESTION_FIELDS = ["rank", "question", "ticket_count", "weighted_frequency", "customer_wording"] as const;

export const DEFLECTION_SNAPSHOT_LOCKED_QUESTION_FIELDS = ["rank", "ticket_count"] as const;

export const DEFLECTION_SNAPSHOT_TOP_BLIND_SPOT_FIELDS = ["rank", "question", "ticket_count"] as const;

export const DEFLECTION_SNAPSHOT_TEASER_FIELDS = ["full_answer", "previews"] as const;

export const DEFLECTION_SNAPSHOT_TEASER_FULL_ANSWER_FIELDS = ["rank", "question", "answer", "steps", "answer_evidence_status", "resolution_evidence_scope", "weighted_frequency", "source_count"] as const;

export const DEFLECTION_SNAPSHOT_TEASER_PREVIEW_FIELDS = ["rank", "question", "answer_evidence_status", "resolution_evidence_scope", "weighted_frequency", "step_count", "source_count", "body_withheld"] as const;

export type DeflectionSnapshotSummary = {
  generated: number;
  drafted_answer_count: number;
  no_proven_answer_count: number;
  support_ticket_resolution_evidence_present: boolean;
  support_ticket_resolution_evidence_count: number;
  repeat_ticket_count: number;
  non_repeat_ticket_count: number;
  source_date_start?: string | null;
  source_date_end?: string | null;
  source_window_days?: number | null;
};

export type DeflectionSnapshotQuestion = {
  rank: number;
  question: string;
  ticket_count: number;
  weighted_frequency: number;
  customer_wording: string;
};

export type DeflectionSnapshotLockedQuestion = {
  rank: number;
  ticket_count: number;
};

export type DeflectionSnapshotBlindSpot = {
  rank: number;
  question: string;
  ticket_count: number;
};

export type DeflectionSnapshotFullAnswer = {
  rank: number;
  question: string;
  answer: string;
  steps: string[];
  answer_evidence_status: string;
  resolution_evidence_scope: string;
  weighted_frequency: number;
  source_count: number;
};

export type DeflectionSnapshotAnswerPreview = {
  rank: number;
  question: string;
  answer_evidence_status: string;
  resolution_evidence_scope: string;
  weighted_frequency: number;
  step_count: number;
  source_count: number;
  body_withheld: boolean;
};

export type DeflectionSnapshotTeaser = {
  full_answer: DeflectionSnapshotFullAnswer | null;
  previews: DeflectionSnapshotAnswerPreview[];
};

export type DeflectionSnapshot = {
  summary: DeflectionSnapshotSummary;
  top_questions: DeflectionSnapshotQuestion[];
  locked_questions: DeflectionSnapshotLockedQuestion[];
  top_blind_spots: DeflectionSnapshotBlindSpot[];
  teaser: DeflectionSnapshotTeaser;
};

export type DeflectionResultPageSnapshot = Pick<DeflectionSnapshot, "summary" | "top_questions" | "top_blind_spots">;

export type DeflectionSnapshotSourceWindow = {
  source_date_start: string;
  source_date_end: string;
  source_window_days: number;
};
