import type { DeflectionStructuredReport } from './deflection-report-contract';

const baseActionItem = {
  rank: 1,
  repeat_key: 'billing-export-attribution',
  cluster_id: 'cluster-billing-export-attribution',
  identity_basis: 'customer_question',
  identity_confidence: 'high',
  question: 'How do I export invoice attribution for finance?',
  status: 'Needs answer',
  owner_lane: 'Help Center',
  fix_type: 'create_missing_answer',
  csat_signal: {
    status: 'sparse',
    csat_present_count: 4,
    negative_csat_ticket_count: 2,
    numeric_average: 2.3,
  },
  confidence: 'high',
  priority_score: 91,
  priority_drivers: ['repeat_volume', 'missing_answer', 'negative_csat'],
  recommended_title: 'Export invoice attribution for finance review',
  recommended_action: 'Draft and publish the missing finance-export article.',
  representative_phrasing: 'export invoice attribution for finance',
  ticket_count: 84,
  estimated_support_cost: 1134,
  support_cost_formula: 'ticket_count * assisted_contact_cost',
  support_cost_source: 'assisted_contact_benchmark',
  opportunity_score: 88,
  top_evidence: [],
};

export const DEMO_DEFLECTION_REPORT_MODEL: DeflectionStructuredReport = {
  schema_version: 'deflection.v1',
  title: 'Demo Resolution Audit',
  summary: {
    generated: 12,
    repeat_ticket_count: 1700,
  },
  sections: [
    {
      id: 'priority_fix_queue',
      title: 'Priority Fix Queue',
      priority: 35,
      surfaces: ['web', 'pdf', 'email_summary'],
      default_limit: 3,
      required_data: [
        'items',
        'status_counts',
        'result_page_limit',
        'pdf_limit',
        'backlog_limit',
        'support_cost_basis',
      ],
      snapshot_safe_fields: [],
      data: {
        items: [baseActionItem],
        status_counts: { 'Needs answer': 5, 'Draft ready': 4, 'Already covered but still recurring': 3 },
        result_page_limit: 3,
        pdf_limit: 10,
        backlog_limit: 25,
        support_cost_basis: {
          status: 'benchmark_only',
          assisted_contact_cost: 13.5,
          formula: 'ticket_count * assisted_contact_cost',
          source: 'assisted_contact_benchmark',
        },
      },
    },
    {
      id: 'top_unresolved_repeats',
      title: 'Top Unresolved Repeats',
      priority: 36,
      surfaces: ['web', 'pdf'],
      default_limit: 3,
      required_data: ['items', 'top_item_count', 'result_page_limit', 'pdf_limit', 'support_cost_basis'],
      snapshot_safe_fields: ['items.rank', 'items.question', 'items.ticket_count'],
      data: {
        items: [baseActionItem],
        top_item_count: 3,
        result_page_limit: 3,
        pdf_limit: 10,
        support_cost_basis: {
          status: 'benchmark_only',
          assisted_contact_cost: 13.5,
          formula: 'ticket_count * assisted_contact_cost',
          source: 'assisted_contact_benchmark',
        },
      },
    },
    {
      id: 'drafted_resolutions',
      title: 'Drafted Resolutions',
      priority: 37,
      surfaces: ['web', 'pdf'],
      default_limit: 3,
      required_data: ['items', 'top_item_count', 'result_page_limit', 'pdf_limit'],
      snapshot_safe_fields: [],
      data: {
        items: [
          {
            ...baseActionItem,
            rank: 2,
            repeat_key: 'reset-sso-enrollment',
            cluster_id: 'cluster-reset-sso-enrollment',
            question: 'How do I reset SSO enrollment?',
            status: 'Draft ready',
            recommended_action: 'Review the drafted SSO reset answer and approve it for the help center.',
            ticket_count: 61,
            estimated_support_cost: 824,
            priority_score: 84,
          },
        ],
        top_item_count: 3,
        result_page_limit: 3,
        pdf_limit: 10,
      },
    },
    {
      id: 'already_covered_still_recurring',
      title: 'Already Covered but Still Recurring',
      priority: 38,
      surfaces: ['web', 'pdf'],
      default_limit: 3,
      required_data: ['items', 'top_item_count', 'result_page_limit', 'pdf_limit'],
      snapshot_safe_fields: [],
      data: {
        items: [
          {
            ...baseActionItem,
            rank: 3,
            repeat_key: 'password-reset-email-missing',
            cluster_id: 'cluster-password-reset-email-missing',
            question: 'Why did the password reset email not arrive?',
            status: 'Already covered but still recurring',
            fix_type: 'improve_discoverability',
            recommended_action: 'Improve help-center wording and check the reset email deliverability path.',
            ticket_count: 49,
            estimated_support_cost: 662,
            priority_score: 79,
          },
        ],
        top_item_count: 3,
        result_page_limit: 3,
        pdf_limit: 10,
      },
    },
    {
      id: 'backlog_table',
      title: 'Backlog Table',
      priority: 39,
      surfaces: ['web', 'pdf', 'export'],
      default_limit: 25,
      required_data: ['items', 'total_item_count', 'default_limit'],
      snapshot_safe_fields: [],
      data: {
        items: [baseActionItem],
        total_item_count: 12,
        default_limit: 25,
      },
    },
    {
      id: 'outcome_diagnostics',
      title: 'Resolution Outcome Diagnostics',
      priority: 40,
      surfaces: ['web', 'pdf'],
      default_limit: 25,
      required_data: [
        'outcome_diagnostic_ticket_count',
        'outcome_risk_ticket_count',
        'reopened_ticket_count',
        'negative_csat_ticket_count',
        'rows',
      ],
      snapshot_safe_fields: [],
      data: {
        outcome_diagnostic_ticket_count: 18,
        outcome_risk_ticket_count: 7,
        reopened_ticket_count: 5,
        negative_csat_ticket_count: 2,
        rows: [
          {
            question: 'Why did the password reset email not arrive?',
            status_mix: { reopened: 5, negative_csat: 2 },
            reopened_ticket_count: 5,
            negative_csat_ticket_count: 2,
            guidance: 'Review the reset-email workflow before publishing more documentation.',
          },
        ],
      },
    },
    {
      id: 'suppressed_repeat_review_queue',
      title: 'Suppressed Repeat Review Queue',
      priority: 41,
      surfaces: ['web', 'export'],
      default_limit: 25,
      required_data: ['items', 'total_item_count', 'default_limit', 'reason_counts'],
      snapshot_safe_fields: [],
      data: {
        items: [
          {
            ...baseActionItem,
            rank: 4,
            repeat_key: 'closed-invoice-contact-change',
            cluster_id: 'cluster-closed-invoice-contact-change',
            question: 'Can I change invoice contacts for a closed invoice?',
            status: 'Review before promotion',
            owner_lane: 'Operations',
            fix_type: 'review_suppressed_repeat',
            recommended_action: 'Review whether this low-volume repeat belongs in the action queue before assigning work.',
            ticket_count: 2,
            estimated_support_cost: 27,
            priority_score: 35,
            priority_drivers: ['suppressed_repeat', 'too_low_volume'],
            suppression_reason: 'too_low_volume',
            suppression_reason_label: 'Too low volume',
          },
        ],
        total_item_count: 1,
        default_limit: 25,
        reason_counts: { too_low_volume: 1 },
      },
    },
    {
      id: 'question_details',
      title: 'Top publishable answers and gaps',
      priority: 50,
      surfaces: ['web', 'pdf'],
      default_limit: 10,
      required_data: ['rows'],
      snapshot_safe_fields: [
        'rows.rank',
        'rows.question',
        'rows.answer_evidence_status',
        'rows.resolution_evidence_scope',
        'rows.weighted_frequency',
        'rows.source_count',
      ],
      data: {
        rows: [
          {
            rank: 1,
            question: 'How do I export invoice attribution for finance?',
            customer_wording: 'export invoice attribution for finance',
            topic: 'Billing exports',
            ticket_count: 84,
            weighted_frequency: 84,
            source_count: 18,
            estimated_support_cost: 1134,
            answer_status: 'Publishable answer found',
            answer_evidence_status: 'agent_backed',
            resolution_evidence_scope: 'specific_steps',
            answer_linkage: 'publishable_answer',
            answer: 'Use the billing export menu, select attribution fields, and download the finance CSV.',
            steps: [
              'Open Billing exports.',
              'Select invoice attribution fields.',
              'Download the finance CSV.',
            ],
            term_mappings: [
              {
                customer_term: 'invoice attribution',
                documentation_term: 'billing export fields',
                suggestion: 'Use both terms in the article title and intro.',
                source_id_count: 18,
              },
            ],
            source_ids: [],
            evidence_quotes: [],
            outcome_diagnostics: {
              ticket_status_summary: { solved: 17, reopened: 1 },
              diagnostic_ticket_count: 18,
              outcome_risk_ticket_count: 1,
              reopened_ticket_count: 1,
              negative_csat_ticket_count: 0,
              csat_present_count: 4,
              csat_score_average: 4.2,
            },
          },
        ],
      },
    },
  ],
};
